package com.mgskj.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class TEquipFaultData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.LocalCenterRegionName
     *
     * @mbggenerated
     */
    private String localcenterregionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.TunnelRegionName
     *
     * @mbggenerated
     */
    private String tunnelregionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.EquipName
     *
     * @mbggenerated
     */
    private String equipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.Module
     *
     * @mbggenerated
     */
    private Integer module;
    private String moduledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.EquipType
     *
     * @mbggenerated
     */
    private Integer equiptype;

    private String equiptypedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.RouteCode
     *
     * @mbggenerated
     */
    private String routecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.Mile
     *
     * @mbggenerated
     */
    private String mile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.Ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.FaultStatus
     *
     * @mbggenerated
     */
    private Integer faultstatus;

    private String faultstatusdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.CreateDate
     *
     * @mbggenerated
     */
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EquipFault_Data.CreateTime
     *
     * @mbggenerated
     */
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EquipFault_Data
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.Id
     *
     * @return the value of T_EquipFault_Data.Id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.Id
     *
     * @param id the value for T_EquipFault_Data.Id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.LocalCenterRegionName
     *
     * @return the value of T_EquipFault_Data.LocalCenterRegionName
     * @mbggenerated
     */
    public String getLocalcenterregionname() {
        return localcenterregionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.LocalCenterRegionName
     *
     * @param localcenterregionname the value for T_EquipFault_Data.LocalCenterRegionName
     * @mbggenerated
     */
    public void setLocalcenterregionname(String localcenterregionname) {
        this.localcenterregionname = localcenterregionname == null ? null : localcenterregionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.TunnelRegionName
     *
     * @return the value of T_EquipFault_Data.TunnelRegionName
     * @mbggenerated
     */
    public String getTunnelregionname() {
        return tunnelregionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.TunnelRegionName
     *
     * @param tunnelregionname the value for T_EquipFault_Data.TunnelRegionName
     * @mbggenerated
     */
    public void setTunnelregionname(String tunnelregionname) {
        this.tunnelregionname = tunnelregionname == null ? null : tunnelregionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.EquipName
     *
     * @return the value of T_EquipFault_Data.EquipName
     * @mbggenerated
     */
    public String getEquipname() {
        return equipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.EquipName
     *
     * @param equipname the value for T_EquipFault_Data.EquipName
     * @mbggenerated
     */
    public void setEquipname(String equipname) {
        this.equipname = equipname == null ? null : equipname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.Module
     *
     * @return the value of T_EquipFault_Data.Module
     * @mbggenerated
     */
    public Integer getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.Module
     *
     * @param module the value for T_EquipFault_Data.Module
     * @mbggenerated
     */
    public void setModule(Integer module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.EquipType
     *
     * @return the value of T_EquipFault_Data.EquipType
     * @mbggenerated
     */
    public Integer getEquiptype() {
        return equiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.EquipType
     *
     * @param equiptype the value for T_EquipFault_Data.EquipType
     * @mbggenerated
     */
    public void setEquiptype(Integer equiptype) {
        this.equiptype = equiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.RouteCode
     *
     * @return the value of T_EquipFault_Data.RouteCode
     * @mbggenerated
     */
    public String getRoutecode() {
        return routecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.RouteCode
     *
     * @param routecode the value for T_EquipFault_Data.RouteCode
     * @mbggenerated
     */
    public void setRoutecode(String routecode) {
        this.routecode = routecode == null ? null : routecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.Mile
     *
     * @return the value of T_EquipFault_Data.Mile
     * @mbggenerated
     */
    public String getMile() {
        return mile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.Mile
     *
     * @param mile the value for T_EquipFault_Data.Mile
     * @mbggenerated
     */
    public void setMile(String mile) {
        this.mile = mile == null ? null : mile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.Ip
     *
     * @return the value of T_EquipFault_Data.Ip
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.Ip
     *
     * @param ip the value for T_EquipFault_Data.Ip
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.FaultStatus
     *
     * @return the value of T_EquipFault_Data.FaultStatus
     * @mbggenerated
     */
    public Integer getFaultstatus() {
        return faultstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.FaultStatus
     *
     * @param faultstatus the value for T_EquipFault_Data.FaultStatus
     * @mbggenerated
     */
    public void setFaultstatus(Integer faultstatus) {
        this.faultstatus = faultstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.CreateDate
     *
     * @return the value of T_EquipFault_Data.CreateDate
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.CreateDate
     *
     * @param createdate the value for T_EquipFault_Data.CreateDate
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EquipFault_Data.CreateTime
     *
     * @return the value of T_EquipFault_Data.CreateTime
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EquipFault_Data.CreateTime
     *
     * @param createtime the value for T_EquipFault_Data.CreateTime
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getEquiptypedesc() {
        return equiptypedesc;
    }

    public void setEquiptypedesc(String equiptypedesc) {
        this.equiptypedesc = equiptypedesc;
    }

    public String getFaultstatusdesc() {
        return faultstatusdesc;
    }

    public void setFaultstatusdesc(String faultstatusdesc) {
        this.faultstatusdesc = faultstatusdesc;
    }

    public String getModuledesc() {
        return moduledesc;
    }

    public void setModuledesc(String moduledesc) {
        this.moduledesc = moduledesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TEquipFaultData that = (TEquipFaultData) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(localcenterregionname, that.localcenterregionname) &&
                Objects.equals(tunnelregionname, that.tunnelregionname) &&
                Objects.equals(equipname, that.equipname) &&
                Objects.equals(module, that.module) &&
                Objects.equals(moduledesc, that.moduledesc) &&
                Objects.equals(equiptype, that.equiptype) &&
                Objects.equals(equiptypedesc, that.equiptypedesc) &&
                Objects.equals(routecode, that.routecode) &&
                Objects.equals(mile, that.mile) &&
                Objects.equals(ip, that.ip) &&
                Objects.equals(faultstatus, that.faultstatus) &&
                Objects.equals(faultstatusdesc, that.faultstatusdesc) &&
                Objects.equals(createdate, that.createdate) &&
                Objects.equals(createtime, that.createtime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, localcenterregionname, tunnelregionname, equipname, module, moduledesc, equiptype, equiptypedesc, routecode, mile, ip, faultstatus, faultstatusdesc, createdate, createtime);
    }

    @Override
    public String toString() {
        return "TEquipFaultData{" +
                "id='" + id + '\'' +
                ", localcenterregionname='" + localcenterregionname + '\'' +
                ", tunnelregionname='" + tunnelregionname + '\'' +
                ", equipname='" + equipname + '\'' +
                ", module=" + module +
                ", moduledesc='" + moduledesc + '\'' +
                ", equiptype=" + equiptype +
                ", equiptypedesc='" + equiptypedesc + '\'' +
                ", routecode='" + routecode + '\'' +
                ", mile='" + mile + '\'' +
                ", ip='" + ip + '\'' +
                ", faultstatus=" + faultstatus +
                ", faultstatusdesc='" + faultstatusdesc + '\'' +
                ", createdate=" + createdate +
                ", createtime=" + createtime +
                '}';
    }
}