package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

public class TEVDAlarmDataW implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.OperationLogWId
     *
     * @mbggenerated
     */
    private String operationlogwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.EVDEquipId
     *
     * @mbggenerated
     */
    private String evdequipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.AlarmType
     *
     * @mbggenerated
     */
    private Integer alarmtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.DealingStatus
     *
     * @mbggenerated
     */
    private Integer dealingstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.Message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.UpdateDate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.UpdateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EVD_AlarmDataW.DuplicateCount
     *
     * @mbggenerated
     */
    private Integer duplicatecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.Id
     *
     * @return the value of T_EVD_AlarmDataW.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.Id
     *
     * @param id the value for T_EVD_AlarmDataW.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.OperationLogWId
     *
     * @return the value of T_EVD_AlarmDataW.OperationLogWId
     *
     * @mbggenerated
     */
    public String getOperationlogwid() {
        return operationlogwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.OperationLogWId
     *
     * @param operationlogwid the value for T_EVD_AlarmDataW.OperationLogWId
     *
     * @mbggenerated
     */
    public void setOperationlogwid(String operationlogwid) {
        this.operationlogwid = operationlogwid == null ? null : operationlogwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.EVDEquipId
     *
     * @return the value of T_EVD_AlarmDataW.EVDEquipId
     *
     * @mbggenerated
     */
    public String getEvdequipid() {
        return evdequipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.EVDEquipId
     *
     * @param evdequipid the value for T_EVD_AlarmDataW.EVDEquipId
     *
     * @mbggenerated
     */
    public void setEvdequipid(String evdequipid) {
        this.evdequipid = evdequipid == null ? null : evdequipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.AlarmType
     *
     * @return the value of T_EVD_AlarmDataW.AlarmType
     *
     * @mbggenerated
     */
    public Integer getAlarmtype() {
        return alarmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.AlarmType
     *
     * @param alarmtype the value for T_EVD_AlarmDataW.AlarmType
     *
     * @mbggenerated
     */
    public void setAlarmtype(Integer alarmtype) {
        this.alarmtype = alarmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.DealingStatus
     *
     * @return the value of T_EVD_AlarmDataW.DealingStatus
     *
     * @mbggenerated
     */
    public Integer getDealingstatus() {
        return dealingstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.DealingStatus
     *
     * @param dealingstatus the value for T_EVD_AlarmDataW.DealingStatus
     *
     * @mbggenerated
     */
    public void setDealingstatus(Integer dealingstatus) {
        this.dealingstatus = dealingstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.Message
     *
     * @return the value of T_EVD_AlarmDataW.Message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.Message
     *
     * @param message the value for T_EVD_AlarmDataW.Message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.CreateDate
     *
     * @return the value of T_EVD_AlarmDataW.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.CreateDate
     *
     * @param createdate the value for T_EVD_AlarmDataW.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.CreateTime
     *
     * @return the value of T_EVD_AlarmDataW.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.CreateTime
     *
     * @param createtime the value for T_EVD_AlarmDataW.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.UpdateDate
     *
     * @return the value of T_EVD_AlarmDataW.UpdateDate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.UpdateDate
     *
     * @param updatedate the value for T_EVD_AlarmDataW.UpdateDate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.UpdateTime
     *
     * @return the value of T_EVD_AlarmDataW.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.UpdateTime
     *
     * @param updatetime the value for T_EVD_AlarmDataW.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EVD_AlarmDataW.DuplicateCount
     *
     * @return the value of T_EVD_AlarmDataW.DuplicateCount
     *
     * @mbggenerated
     */
    public Integer getDuplicatecount() {
        return duplicatecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EVD_AlarmDataW.DuplicateCount
     *
     * @param duplicatecount the value for T_EVD_AlarmDataW.DuplicateCount
     *
     * @mbggenerated
     */
    public void setDuplicatecount(Integer duplicatecount) {
        this.duplicatecount = duplicatecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TEVDAlarmDataW other = (TEVDAlarmDataW) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperationlogwid() == null ? other.getOperationlogwid() == null : this.getOperationlogwid().equals(other.getOperationlogwid()))
            && (this.getEvdequipid() == null ? other.getEvdequipid() == null : this.getEvdequipid().equals(other.getEvdequipid()))
            && (this.getAlarmtype() == null ? other.getAlarmtype() == null : this.getAlarmtype().equals(other.getAlarmtype()))
            && (this.getDealingstatus() == null ? other.getDealingstatus() == null : this.getDealingstatus().equals(other.getDealingstatus()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatedate() == null ? other.getUpdatedate() == null : this.getUpdatedate().equals(other.getUpdatedate()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getDuplicatecount() == null ? other.getDuplicatecount() == null : this.getDuplicatecount().equals(other.getDuplicatecount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperationlogwid() == null) ? 0 : getOperationlogwid().hashCode());
        result = prime * result + ((getEvdequipid() == null) ? 0 : getEvdequipid().hashCode());
        result = prime * result + ((getAlarmtype() == null) ? 0 : getAlarmtype().hashCode());
        result = prime * result + ((getDealingstatus() == null) ? 0 : getDealingstatus().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatedate() == null) ? 0 : getUpdatedate().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getDuplicatecount() == null) ? 0 : getDuplicatecount().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operationlogwid=").append(operationlogwid);
        sb.append(", evdequipid=").append(evdequipid);
        sb.append(", alarmtype=").append(alarmtype);
        sb.append(", dealingstatus=").append(dealingstatus);
        sb.append(", message=").append(message);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", duplicatecount=").append(duplicatecount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}