package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

public class TOperationLogW implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.ParentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.EmployeeId
     *
     * @mbggenerated
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.SourceModule
     *
     * @mbggenerated
     */
    private Integer sourcemodule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.Operation
     *
     * @mbggenerated
     */
    private Integer operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.Target
     *
     * @mbggenerated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.Result
     *
     * @mbggenerated
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.Id
     *
     * @return the value of T_OperationLogW.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.Id
     *
     * @param id the value for T_OperationLogW.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.ParentId
     *
     * @return the value of T_OperationLogW.ParentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.ParentId
     *
     * @param parentid the value for T_OperationLogW.ParentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.EmployeeId
     *
     * @return the value of T_OperationLogW.EmployeeId
     *
     * @mbggenerated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.EmployeeId
     *
     * @param employeeid the value for T_OperationLogW.EmployeeId
     *
     * @mbggenerated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.UserName
     *
     * @return the value of T_OperationLogW.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.UserName
     *
     * @param username the value for T_OperationLogW.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.SourceModule
     *
     * @return the value of T_OperationLogW.SourceModule
     *
     * @mbggenerated
     */
    public Integer getSourcemodule() {
        return sourcemodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.SourceModule
     *
     * @param sourcemodule the value for T_OperationLogW.SourceModule
     *
     * @mbggenerated
     */
    public void setSourcemodule(Integer sourcemodule) {
        this.sourcemodule = sourcemodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.Operation
     *
     * @return the value of T_OperationLogW.Operation
     *
     * @mbggenerated
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.Operation
     *
     * @param operation the value for T_OperationLogW.Operation
     *
     * @mbggenerated
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.Target
     *
     * @return the value of T_OperationLogW.Target
     *
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.Target
     *
     * @param target the value for T_OperationLogW.Target
     *
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.Description
     *
     * @return the value of T_OperationLogW.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.Description
     *
     * @param description the value for T_OperationLogW.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.Result
     *
     * @return the value of T_OperationLogW.Result
     *
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.Result
     *
     * @param result the value for T_OperationLogW.Result
     *
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.CreateDate
     *
     * @return the value of T_OperationLogW.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.CreateDate
     *
     * @param createdate the value for T_OperationLogW.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW.CreateTime
     *
     * @return the value of T_OperationLogW.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW.CreateTime
     *
     * @param createtime the value for T_OperationLogW.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TOperationLogW other = (TOperationLogW) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getSourcemodule() == null ? other.getSourcemodule() == null : this.getSourcemodule().equals(other.getSourcemodule()))
            && (this.getOperation() == null ? other.getOperation() == null : this.getOperation().equals(other.getOperation()))
            && (this.getTarget() == null ? other.getTarget() == null : this.getTarget().equals(other.getTarget()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getSourcemodule() == null) ? 0 : getSourcemodule().hashCode());
        result = prime * result + ((getOperation() == null) ? 0 : getOperation().hashCode());
        result = prime * result + ((getTarget() == null) ? 0 : getTarget().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentid=").append(parentid);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", username=").append(username);
        sb.append(", sourcemodule=").append(sourcemodule);
        sb.append(", operation=").append(operation);
        sb.append(", target=").append(target);
        sb.append(", description=").append(description);
        sb.append(", result=").append(result);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}