package com.mgskj.model;

import java.io.Serializable;

public class TOperationLogWCMSControlW implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.OperationLogId
     *
     * @mbggenerated
     */
    private Integer operationlogwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.CMSId
     *
     * @mbggenerated
     */
    private String cmsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.ContentText
     *
     * @mbggenerated
     */
    private String contenttext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.FontName
     *
     * @mbggenerated
     */
    private String fontname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.FontSize
     *
     * @mbggenerated
     */
    private Integer fontsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.FontColor
     *
     * @mbggenerated
     */
    private Integer fontcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.TextX
     *
     * @mbggenerated
     */
    private String textx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.TextY
     *
     * @mbggenerated
     */
    private String texty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.WordSpace
     *
     * @mbggenerated
     */
    private Integer wordspace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.LineSpace
     *
     * @mbggenerated
     */
    private Integer linespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.BackColor
     *
     * @mbggenerated
     */
    private Integer backcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.EnterEffect
     *
     * @mbggenerated
     */
    private Integer entereffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.StickTime
     *
     * @mbggenerated
     */
    private Integer sticktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.InfoType
     *
     * @mbggenerated
     */
    private Integer infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.Width
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.Height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.ProtocolId
     *
     * @mbggenerated
     */
    private Integer protocolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.Situation
     *
     * @mbggenerated
     */
    private Integer situation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.IsLockedByCityCenter
     *
     * @mbggenerated
     */
    private Boolean islockedbycitycenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.IsImportant
     *
     * @mbggenerated
     */
    private Boolean isimportant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OperationLogW_CMS_ControlW.FlashLightOperation
     *
     * @mbggenerated
     */
    private Integer flashlightoperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.Id
     *
     * @return the value of T_OperationLogW_CMS_ControlW.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.Id
     *
     * @param id the value for T_OperationLogW_CMS_ControlW.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.OperationLogId
     *
     * @return the value of T_OperationLogW_CMS_ControlW.OperationLogId
     *
     * @mbggenerated
     */
    public Integer getOperationlogid() {
        return operationlogwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.OperationLogId
     *
     * @param operationlogid the value for T_OperationLogW_CMS_ControlW.OperationLogId
     *
     * @mbggenerated
     */
    public void setOperationlogid(Integer operationlogid) {
        this.operationlogwid = operationlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.CMSId
     *
     * @return the value of T_OperationLogW_CMS_ControlW.CMSId
     *
     * @mbggenerated
     */
    public String getCmsid() {
        return cmsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.CMSId
     *
     * @param cmsid the value for T_OperationLogW_CMS_ControlW.CMSId
     *
     * @mbggenerated
     */
    public void setCmsid(String cmsid) {
        this.cmsid = cmsid == null ? null : cmsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.ContentText
     *
     * @return the value of T_OperationLogW_CMS_ControlW.ContentText
     *
     * @mbggenerated
     */
    public String getContenttext() {
        return contenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.ContentText
     *
     * @param contenttext the value for T_OperationLogW_CMS_ControlW.ContentText
     *
     * @mbggenerated
     */
    public void setContenttext(String contenttext) {
        this.contenttext = contenttext == null ? null : contenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.FontName
     *
     * @return the value of T_OperationLogW_CMS_ControlW.FontName
     *
     * @mbggenerated
     */
    public String getFontname() {
        return fontname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.FontName
     *
     * @param fontname the value for T_OperationLogW_CMS_ControlW.FontName
     *
     * @mbggenerated
     */
    public void setFontname(String fontname) {
        this.fontname = fontname == null ? null : fontname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.FontSize
     *
     * @return the value of T_OperationLogW_CMS_ControlW.FontSize
     *
     * @mbggenerated
     */
    public Integer getFontsize() {
        return fontsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.FontSize
     *
     * @param fontsize the value for T_OperationLogW_CMS_ControlW.FontSize
     *
     * @mbggenerated
     */
    public void setFontsize(Integer fontsize) {
        this.fontsize = fontsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.FontColor
     *
     * @return the value of T_OperationLogW_CMS_ControlW.FontColor
     *
     * @mbggenerated
     */
    public Integer getFontcolor() {
        return fontcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.FontColor
     *
     * @param fontcolor the value for T_OperationLogW_CMS_ControlW.FontColor
     *
     * @mbggenerated
     */
    public void setFontcolor(Integer fontcolor) {
        this.fontcolor = fontcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.TextX
     *
     * @return the value of T_OperationLogW_CMS_ControlW.TextX
     *
     * @mbggenerated
     */
    public String getTextx() {
        return textx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.TextX
     *
     * @param textx the value for T_OperationLogW_CMS_ControlW.TextX
     *
     * @mbggenerated
     */
    public void setTextx(String textx) {
        this.textx = textx == null ? null : textx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.TextY
     *
     * @return the value of T_OperationLogW_CMS_ControlW.TextY
     *
     * @mbggenerated
     */
    public String getTexty() {
        return texty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.TextY
     *
     * @param texty the value for T_OperationLogW_CMS_ControlW.TextY
     *
     * @mbggenerated
     */
    public void setTexty(String texty) {
        this.texty = texty == null ? null : texty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.WordSpace
     *
     * @return the value of T_OperationLogW_CMS_ControlW.WordSpace
     *
     * @mbggenerated
     */
    public Integer getWordspace() {
        return wordspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.WordSpace
     *
     * @param wordspace the value for T_OperationLogW_CMS_ControlW.WordSpace
     *
     * @mbggenerated
     */
    public void setWordspace(Integer wordspace) {
        this.wordspace = wordspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.LineSpace
     *
     * @return the value of T_OperationLogW_CMS_ControlW.LineSpace
     *
     * @mbggenerated
     */
    public Integer getLinespace() {
        return linespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.LineSpace
     *
     * @param linespace the value for T_OperationLogW_CMS_ControlW.LineSpace
     *
     * @mbggenerated
     */
    public void setLinespace(Integer linespace) {
        this.linespace = linespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.BackColor
     *
     * @return the value of T_OperationLogW_CMS_ControlW.BackColor
     *
     * @mbggenerated
     */
    public Integer getBackcolor() {
        return backcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.BackColor
     *
     * @param backcolor the value for T_OperationLogW_CMS_ControlW.BackColor
     *
     * @mbggenerated
     */
    public void setBackcolor(Integer backcolor) {
        this.backcolor = backcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.EnterEffect
     *
     * @return the value of T_OperationLogW_CMS_ControlW.EnterEffect
     *
     * @mbggenerated
     */
    public Integer getEntereffect() {
        return entereffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.EnterEffect
     *
     * @param entereffect the value for T_OperationLogW_CMS_ControlW.EnterEffect
     *
     * @mbggenerated
     */
    public void setEntereffect(Integer entereffect) {
        this.entereffect = entereffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.StickTime
     *
     * @return the value of T_OperationLogW_CMS_ControlW.StickTime
     *
     * @mbggenerated
     */
    public Integer getSticktime() {
        return sticktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.StickTime
     *
     * @param sticktime the value for T_OperationLogW_CMS_ControlW.StickTime
     *
     * @mbggenerated
     */
    public void setSticktime(Integer sticktime) {
        this.sticktime = sticktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.InfoType
     *
     * @return the value of T_OperationLogW_CMS_ControlW.InfoType
     *
     * @mbggenerated
     */
    public Integer getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.InfoType
     *
     * @param infotype the value for T_OperationLogW_CMS_ControlW.InfoType
     *
     * @mbggenerated
     */
    public void setInfotype(Integer infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.Width
     *
     * @return the value of T_OperationLogW_CMS_ControlW.Width
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.Width
     *
     * @param width the value for T_OperationLogW_CMS_ControlW.Width
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.Height
     *
     * @return the value of T_OperationLogW_CMS_ControlW.Height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.Height
     *
     * @param height the value for T_OperationLogW_CMS_ControlW.Height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.ProtocolId
     *
     * @return the value of T_OperationLogW_CMS_ControlW.ProtocolId
     *
     * @mbggenerated
     */
    public Integer getProtocolid() {
        return protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.ProtocolId
     *
     * @param protocolid the value for T_OperationLogW_CMS_ControlW.ProtocolId
     *
     * @mbggenerated
     */
    public void setProtocolid(Integer protocolid) {
        this.protocolid = protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.Situation
     *
     * @return the value of T_OperationLogW_CMS_ControlW.Situation
     *
     * @mbggenerated
     */
    public Integer getSituation() {
        return situation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.Situation
     *
     * @param situation the value for T_OperationLogW_CMS_ControlW.Situation
     *
     * @mbggenerated
     */
    public void setSituation(Integer situation) {
        this.situation = situation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.IsLockedByCityCenter
     *
     * @return the value of T_OperationLogW_CMS_ControlW.IsLockedByCityCenter
     *
     * @mbggenerated
     */
    public Boolean getIslockedbycitycenter() {
        return islockedbycitycenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.IsLockedByCityCenter
     *
     * @param islockedbycitycenter the value for T_OperationLogW_CMS_ControlW.IsLockedByCityCenter
     *
     * @mbggenerated
     */
    public void setIslockedbycitycenter(Boolean islockedbycitycenter) {
        this.islockedbycitycenter = islockedbycitycenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.IsImportant
     *
     * @return the value of T_OperationLogW_CMS_ControlW.IsImportant
     *
     * @mbggenerated
     */
    public Boolean getIsimportant() {
        return isimportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.IsImportant
     *
     * @param isimportant the value for T_OperationLogW_CMS_ControlW.IsImportant
     *
     * @mbggenerated
     */
    public void setIsimportant(Boolean isimportant) {
        this.isimportant = isimportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OperationLogW_CMS_ControlW.FlashLightOperation
     *
     * @return the value of T_OperationLogW_CMS_ControlW.FlashLightOperation
     *
     * @mbggenerated
     */
    public Integer getFlashlightoperation() {
        return flashlightoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OperationLogW_CMS_ControlW.FlashLightOperation
     *
     * @param flashlightoperation the value for T_OperationLogW_CMS_ControlW.FlashLightOperation
     *
     * @mbggenerated
     */
    public void setFlashlightoperation(Integer flashlightoperation) {
        this.flashlightoperation = flashlightoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TOperationLogWCMSControlW other = (TOperationLogWCMSControlW) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperationlogid() == null ? other.getOperationlogid() == null : this.getOperationlogid().equals(other.getOperationlogid()))
            && (this.getCmsid() == null ? other.getCmsid() == null : this.getCmsid().equals(other.getCmsid()))
            && (this.getContenttext() == null ? other.getContenttext() == null : this.getContenttext().equals(other.getContenttext()))
            && (this.getFontname() == null ? other.getFontname() == null : this.getFontname().equals(other.getFontname()))
            && (this.getFontsize() == null ? other.getFontsize() == null : this.getFontsize().equals(other.getFontsize()))
            && (this.getFontcolor() == null ? other.getFontcolor() == null : this.getFontcolor().equals(other.getFontcolor()))
            && (this.getTextx() == null ? other.getTextx() == null : this.getTextx().equals(other.getTextx()))
            && (this.getTexty() == null ? other.getTexty() == null : this.getTexty().equals(other.getTexty()))
            && (this.getWordspace() == null ? other.getWordspace() == null : this.getWordspace().equals(other.getWordspace()))
            && (this.getLinespace() == null ? other.getLinespace() == null : this.getLinespace().equals(other.getLinespace()))
            && (this.getBackcolor() == null ? other.getBackcolor() == null : this.getBackcolor().equals(other.getBackcolor()))
            && (this.getEntereffect() == null ? other.getEntereffect() == null : this.getEntereffect().equals(other.getEntereffect()))
            && (this.getSticktime() == null ? other.getSticktime() == null : this.getSticktime().equals(other.getSticktime()))
            && (this.getInfotype() == null ? other.getInfotype() == null : this.getInfotype().equals(other.getInfotype()))
            && (this.getWidth() == null ? other.getWidth() == null : this.getWidth().equals(other.getWidth()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()))
            && (this.getProtocolid() == null ? other.getProtocolid() == null : this.getProtocolid().equals(other.getProtocolid()))
            && (this.getSituation() == null ? other.getSituation() == null : this.getSituation().equals(other.getSituation()))
            && (this.getIslockedbycitycenter() == null ? other.getIslockedbycitycenter() == null : this.getIslockedbycitycenter().equals(other.getIslockedbycitycenter()))
            && (this.getIsimportant() == null ? other.getIsimportant() == null : this.getIsimportant().equals(other.getIsimportant()))
            && (this.getFlashlightoperation() == null ? other.getFlashlightoperation() == null : this.getFlashlightoperation().equals(other.getFlashlightoperation()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperationlogid() == null) ? 0 : getOperationlogid().hashCode());
        result = prime * result + ((getCmsid() == null) ? 0 : getCmsid().hashCode());
        result = prime * result + ((getContenttext() == null) ? 0 : getContenttext().hashCode());
        result = prime * result + ((getFontname() == null) ? 0 : getFontname().hashCode());
        result = prime * result + ((getFontsize() == null) ? 0 : getFontsize().hashCode());
        result = prime * result + ((getFontcolor() == null) ? 0 : getFontcolor().hashCode());
        result = prime * result + ((getTextx() == null) ? 0 : getTextx().hashCode());
        result = prime * result + ((getTexty() == null) ? 0 : getTexty().hashCode());
        result = prime * result + ((getWordspace() == null) ? 0 : getWordspace().hashCode());
        result = prime * result + ((getLinespace() == null) ? 0 : getLinespace().hashCode());
        result = prime * result + ((getBackcolor() == null) ? 0 : getBackcolor().hashCode());
        result = prime * result + ((getEntereffect() == null) ? 0 : getEntereffect().hashCode());
        result = prime * result + ((getSticktime() == null) ? 0 : getSticktime().hashCode());
        result = prime * result + ((getInfotype() == null) ? 0 : getInfotype().hashCode());
        result = prime * result + ((getWidth() == null) ? 0 : getWidth().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        result = prime * result + ((getProtocolid() == null) ? 0 : getProtocolid().hashCode());
        result = prime * result + ((getSituation() == null) ? 0 : getSituation().hashCode());
        result = prime * result + ((getIslockedbycitycenter() == null) ? 0 : getIslockedbycitycenter().hashCode());
        result = prime * result + ((getIsimportant() == null) ? 0 : getIsimportant().hashCode());
        result = prime * result + ((getFlashlightoperation() == null) ? 0 : getFlashlightoperation().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operationlogid=").append(operationlogwid);
        sb.append(", cmsid=").append(cmsid);
        sb.append(", contenttext=").append(contenttext);
        sb.append(", fontname=").append(fontname);
        sb.append(", fontsize=").append(fontsize);
        sb.append(", fontcolor=").append(fontcolor);
        sb.append(", textx=").append(textx);
        sb.append(", texty=").append(texty);
        sb.append(", wordspace=").append(wordspace);
        sb.append(", linespace=").append(linespace);
        sb.append(", backcolor=").append(backcolor);
        sb.append(", entereffect=").append(entereffect);
        sb.append(", sticktime=").append(sticktime);
        sb.append(", infotype=").append(infotype);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", protocolid=").append(protocolid);
        sb.append(", situation=").append(situation);
        sb.append(", islockedbycitycenter=").append(islockedbycitycenter);
        sb.append(", isimportant=").append(isimportant);
        sb.append(", flashlightoperation=").append(flashlightoperation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}