package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

public class TRegionInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.ParentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.RegionCode
     *
     * @mbggenerated
     */
    private String regioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.PrefixLength
     *
     * @mbggenerated
     */
    private Integer prefixlength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.RegionType
     *
     * @mbggenerated
     */
    private Integer regiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.RegionName
     *
     * @mbggenerated
     */
    private String regionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.RegionNameEn
     *
     * @mbggenerated
     */
    private String regionnameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.RouteCode
     *
     * @mbggenerated
     */
    private String routecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.OPCItemPrefix
     *
     * @mbggenerated
     */
    private String opcitemprefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RegionInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    private byte[] concurrencytoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.Id
     *
     * @return the value of T_RegionInfo.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.Id
     *
     * @param id the value for T_RegionInfo.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.ParentId
     *
     * @return the value of T_RegionInfo.ParentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.ParentId
     *
     * @param parentid the value for T_RegionInfo.ParentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.RegionCode
     *
     * @return the value of T_RegionInfo.RegionCode
     *
     * @mbggenerated
     */
    public String getRegioncode() {
        return regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.RegionCode
     *
     * @param regioncode the value for T_RegionInfo.RegionCode
     *
     * @mbggenerated
     */
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode == null ? null : regioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.PrefixLength
     *
     * @return the value of T_RegionInfo.PrefixLength
     *
     * @mbggenerated
     */
    public Integer getPrefixlength() {
        return prefixlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.PrefixLength
     *
     * @param prefixlength the value for T_RegionInfo.PrefixLength
     *
     * @mbggenerated
     */
    public void setPrefixlength(Integer prefixlength) {
        this.prefixlength = prefixlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.RegionType
     *
     * @return the value of T_RegionInfo.RegionType
     *
     * @mbggenerated
     */
    public Integer getRegiontype() {
        return regiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.RegionType
     *
     * @param regiontype the value for T_RegionInfo.RegionType
     *
     * @mbggenerated
     */
    public void setRegiontype(Integer regiontype) {
        this.regiontype = regiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.RegionName
     *
     * @return the value of T_RegionInfo.RegionName
     *
     * @mbggenerated
     */
    public String getRegionname() {
        return regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.RegionName
     *
     * @param regionname the value for T_RegionInfo.RegionName
     *
     * @mbggenerated
     */
    public void setRegionname(String regionname) {
        this.regionname = regionname == null ? null : regionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.RegionNameEn
     *
     * @return the value of T_RegionInfo.RegionNameEn
     *
     * @mbggenerated
     */
    public String getRegionnameen() {
        return regionnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.RegionNameEn
     *
     * @param regionnameen the value for T_RegionInfo.RegionNameEn
     *
     * @mbggenerated
     */
    public void setRegionnameen(String regionnameen) {
        this.regionnameen = regionnameen == null ? null : regionnameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.RouteCode
     *
     * @return the value of T_RegionInfo.RouteCode
     *
     * @mbggenerated
     */
    public String getRoutecode() {
        return routecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.RouteCode
     *
     * @param routecode the value for T_RegionInfo.RouteCode
     *
     * @mbggenerated
     */
    public void setRoutecode(String routecode) {
        this.routecode = routecode == null ? null : routecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.OPCItemPrefix
     *
     * @return the value of T_RegionInfo.OPCItemPrefix
     *
     * @mbggenerated
     */
    public String getOpcitemprefix() {
        return opcitemprefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.OPCItemPrefix
     *
     * @param opcitemprefix the value for T_RegionInfo.OPCItemPrefix
     *
     * @mbggenerated
     */
    public void setOpcitemprefix(String opcitemprefix) {
        this.opcitemprefix = opcitemprefix == null ? null : opcitemprefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.CreateDate
     *
     * @return the value of T_RegionInfo.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.CreateDate
     *
     * @param createdate the value for T_RegionInfo.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.CreateTime
     *
     * @return the value of T_RegionInfo.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.CreateTime
     *
     * @param createtime the value for T_RegionInfo.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RegionInfo.ConcurrencyToken
     *
     * @return the value of T_RegionInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    public byte[] getConcurrencytoken() {
        return concurrencytoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RegionInfo.ConcurrencyToken
     *
     * @param concurrencytoken the value for T_RegionInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    public void setConcurrencytoken(byte[] concurrencytoken) {
        this.concurrencytoken = concurrencytoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TRegionInfo other = (TRegionInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getRegioncode() == null ? other.getRegioncode() == null : this.getRegioncode().equals(other.getRegioncode()))
            && (this.getPrefixlength() == null ? other.getPrefixlength() == null : this.getPrefixlength().equals(other.getPrefixlength()))
            && (this.getRegiontype() == null ? other.getRegiontype() == null : this.getRegiontype().equals(other.getRegiontype()))
            && (this.getRegionname() == null ? other.getRegionname() == null : this.getRegionname().equals(other.getRegionname()))
            && (this.getRegionnameen() == null ? other.getRegionnameen() == null : this.getRegionnameen().equals(other.getRegionnameen()))
            && (this.getRoutecode() == null ? other.getRoutecode() == null : this.getRoutecode().equals(other.getRoutecode()))
            && (this.getOpcitemprefix() == null ? other.getOpcitemprefix() == null : this.getOpcitemprefix().equals(other.getOpcitemprefix()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getConcurrencytoken() == null ? other.getConcurrencytoken() == null : this.getConcurrencytoken().equals(other.getConcurrencytoken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getRegioncode() == null) ? 0 : getRegioncode().hashCode());
        result = prime * result + ((getPrefixlength() == null) ? 0 : getPrefixlength().hashCode());
        result = prime * result + ((getRegiontype() == null) ? 0 : getRegiontype().hashCode());
        result = prime * result + ((getRegionname() == null) ? 0 : getRegionname().hashCode());
        result = prime * result + ((getRegionnameen() == null) ? 0 : getRegionnameen().hashCode());
        result = prime * result + ((getRoutecode() == null) ? 0 : getRoutecode().hashCode());
        result = prime * result + ((getOpcitemprefix() == null) ? 0 : getOpcitemprefix().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getConcurrencytoken() == null) ? 0 : getConcurrencytoken().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentid=").append(parentid);
        sb.append(", regioncode=").append(regioncode);
        sb.append(", prefixlength=").append(prefixlength);
        sb.append(", regiontype=").append(regiontype);
        sb.append(", regionname=").append(regionname);
        sb.append(", regionnameen=").append(regionnameen);
        sb.append(", routecode=").append(routecode);
        sb.append(", opcitemprefix=").append(opcitemprefix);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", concurrencytoken=").append(concurrencytoken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}