package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;
/**
 * 车检器
 * @author shenchanghui
 *
 */
public class TVDDataHour implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.EquipId
     *
     * @mbggenerated
     */
    private String equipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.AvgSpd1
     *
     * @mbggenerated
     */
    private Double avgspd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Forward1
     *
     * @mbggenerated
     */
    private Integer forward1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Reverse1
     *
     * @mbggenerated
     */
    private Integer reverse1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Occupancy1
     *
     * @mbggenerated
     */
    private Double occupancy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.AvgSpd2
     *
     * @mbggenerated
     */
    private Double avgspd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Forward2
     *
     * @mbggenerated
     */
    private Integer forward2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Reverse2
     *
     * @mbggenerated
     */
    private Integer reverse2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Occupancy2
     *
     * @mbggenerated
     */
    private Double occupancy2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.AvgSpd3
     *
     * @mbggenerated
     */
    private Double avgspd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Forward3
     *
     * @mbggenerated
     */
    private Integer forward3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Reverse3
     *
     * @mbggenerated
     */
    private Integer reverse3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Occupancy3
     *
     * @mbggenerated
     */
    private Double occupancy3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.AvgSpd4
     *
     * @mbggenerated
     */
    private Double avgspd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Forward4
     *
     * @mbggenerated
     */
    private Integer forward4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Reverse4
     *
     * @mbggenerated
     */
    private Integer reverse4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Occupancy4
     *
     * @mbggenerated
     */
    private Double occupancy4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.AvgSpd5
     *
     * @mbggenerated
     */
    private Double avgspd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Forward5
     *
     * @mbggenerated
     */
    private Integer forward5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Reverse5
     *
     * @mbggenerated
     */
    private Integer reverse5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.Occupancy5
     *
     * @mbggenerated
     */
    private Double occupancy5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.StatisticsCount
     *
     * @mbggenerated
     */
    private Integer statisticscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.GatherDate
     *
     * @mbggenerated
     */
    private Date gatherdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.GatherTime
     *
     * @mbggenerated
     */
    private Date gathertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VD_Data_Hour.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Id
     *
     * @return the value of T_VD_Data_Hour.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Id
     *
     * @param id the value for T_VD_Data_Hour.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.EquipId
     *
     * @return the value of T_VD_Data_Hour.EquipId
     *
     * @mbggenerated
     */
    public String getEquipid() {
        return equipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.EquipId
     *
     * @param equipid the value for T_VD_Data_Hour.EquipId
     *
     * @mbggenerated
     */
    public void setEquipid(String equipid) {
        this.equipid = equipid == null ? null : equipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.AvgSpd1
     *
     * @return the value of T_VD_Data_Hour.AvgSpd1
     *
     * @mbggenerated
     */
    public Double getAvgspd1() {
        return avgspd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.AvgSpd1
     *
     * @param avgspd1 the value for T_VD_Data_Hour.AvgSpd1
     *
     * @mbggenerated
     */
    public void setAvgspd1(Double avgspd1) {
        this.avgspd1 = avgspd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Forward1
     *
     * @return the value of T_VD_Data_Hour.Forward1
     *
     * @mbggenerated
     */
    public Integer getForward1() {
        return forward1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Forward1
     *
     * @param forward1 the value for T_VD_Data_Hour.Forward1
     *
     * @mbggenerated
     */
    public void setForward1(Integer forward1) {
        this.forward1 = forward1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Reverse1
     *
     * @return the value of T_VD_Data_Hour.Reverse1
     *
     * @mbggenerated
     */
    public Integer getReverse1() {
        return reverse1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Reverse1
     *
     * @param reverse1 the value for T_VD_Data_Hour.Reverse1
     *
     * @mbggenerated
     */
    public void setReverse1(Integer reverse1) {
        this.reverse1 = reverse1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Occupancy1
     *
     * @return the value of T_VD_Data_Hour.Occupancy1
     *
     * @mbggenerated
     */
    public Double getOccupancy1() {
        return occupancy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Occupancy1
     *
     * @param occupancy1 the value for T_VD_Data_Hour.Occupancy1
     *
     * @mbggenerated
     */
    public void setOccupancy1(Double occupancy1) {
        this.occupancy1 = occupancy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.AvgSpd2
     *
     * @return the value of T_VD_Data_Hour.AvgSpd2
     *
     * @mbggenerated
     */
    public Double getAvgspd2() {
        return avgspd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.AvgSpd2
     *
     * @param avgspd2 the value for T_VD_Data_Hour.AvgSpd2
     *
     * @mbggenerated
     */
    public void setAvgspd2(Double avgspd2) {
        this.avgspd2 = avgspd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Forward2
     *
     * @return the value of T_VD_Data_Hour.Forward2
     *
     * @mbggenerated
     */
    public Integer getForward2() {
        return forward2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Forward2
     *
     * @param forward2 the value for T_VD_Data_Hour.Forward2
     *
     * @mbggenerated
     */
    public void setForward2(Integer forward2) {
        this.forward2 = forward2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Reverse2
     *
     * @return the value of T_VD_Data_Hour.Reverse2
     *
     * @mbggenerated
     */
    public Integer getReverse2() {
        return reverse2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Reverse2
     *
     * @param reverse2 the value for T_VD_Data_Hour.Reverse2
     *
     * @mbggenerated
     */
    public void setReverse2(Integer reverse2) {
        this.reverse2 = reverse2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Occupancy2
     *
     * @return the value of T_VD_Data_Hour.Occupancy2
     *
     * @mbggenerated
     */
    public Double getOccupancy2() {
        return occupancy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Occupancy2
     *
     * @param occupancy2 the value for T_VD_Data_Hour.Occupancy2
     *
     * @mbggenerated
     */
    public void setOccupancy2(Double occupancy2) {
        this.occupancy2 = occupancy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.AvgSpd3
     *
     * @return the value of T_VD_Data_Hour.AvgSpd3
     *
     * @mbggenerated
     */
    public Double getAvgspd3() {
        return avgspd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.AvgSpd3
     *
     * @param avgspd3 the value for T_VD_Data_Hour.AvgSpd3
     *
     * @mbggenerated
     */
    public void setAvgspd3(Double avgspd3) {
        this.avgspd3 = avgspd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Forward3
     *
     * @return the value of T_VD_Data_Hour.Forward3
     *
     * @mbggenerated
     */
    public Integer getForward3() {
        return forward3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Forward3
     *
     * @param forward3 the value for T_VD_Data_Hour.Forward3
     *
     * @mbggenerated
     */
    public void setForward3(Integer forward3) {
        this.forward3 = forward3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Reverse3
     *
     * @return the value of T_VD_Data_Hour.Reverse3
     *
     * @mbggenerated
     */
    public Integer getReverse3() {
        return reverse3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Reverse3
     *
     * @param reverse3 the value for T_VD_Data_Hour.Reverse3
     *
     * @mbggenerated
     */
    public void setReverse3(Integer reverse3) {
        this.reverse3 = reverse3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Occupancy3
     *
     * @return the value of T_VD_Data_Hour.Occupancy3
     *
     * @mbggenerated
     */
    public Double getOccupancy3() {
        return occupancy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Occupancy3
     *
     * @param occupancy3 the value for T_VD_Data_Hour.Occupancy3
     *
     * @mbggenerated
     */
    public void setOccupancy3(Double occupancy3) {
        this.occupancy3 = occupancy3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.AvgSpd4
     *
     * @return the value of T_VD_Data_Hour.AvgSpd4
     *
     * @mbggenerated
     */
    public Double getAvgspd4() {
        return avgspd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.AvgSpd4
     *
     * @param avgspd4 the value for T_VD_Data_Hour.AvgSpd4
     *
     * @mbggenerated
     */
    public void setAvgspd4(Double avgspd4) {
        this.avgspd4 = avgspd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Forward4
     *
     * @return the value of T_VD_Data_Hour.Forward4
     *
     * @mbggenerated
     */
    public Integer getForward4() {
        return forward4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Forward4
     *
     * @param forward4 the value for T_VD_Data_Hour.Forward4
     *
     * @mbggenerated
     */
    public void setForward4(Integer forward4) {
        this.forward4 = forward4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Reverse4
     *
     * @return the value of T_VD_Data_Hour.Reverse4
     *
     * @mbggenerated
     */
    public Integer getReverse4() {
        return reverse4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Reverse4
     *
     * @param reverse4 the value for T_VD_Data_Hour.Reverse4
     *
     * @mbggenerated
     */
    public void setReverse4(Integer reverse4) {
        this.reverse4 = reverse4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Occupancy4
     *
     * @return the value of T_VD_Data_Hour.Occupancy4
     *
     * @mbggenerated
     */
    public Double getOccupancy4() {
        return occupancy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Occupancy4
     *
     * @param occupancy4 the value for T_VD_Data_Hour.Occupancy4
     *
     * @mbggenerated
     */
    public void setOccupancy4(Double occupancy4) {
        this.occupancy4 = occupancy4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.AvgSpd5
     *
     * @return the value of T_VD_Data_Hour.AvgSpd5
     *
     * @mbggenerated
     */
    public Double getAvgspd5() {
        return avgspd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.AvgSpd5
     *
     * @param avgspd5 the value for T_VD_Data_Hour.AvgSpd5
     *
     * @mbggenerated
     */
    public void setAvgspd5(Double avgspd5) {
        this.avgspd5 = avgspd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Forward5
     *
     * @return the value of T_VD_Data_Hour.Forward5
     *
     * @mbggenerated
     */
    public Integer getForward5() {
        return forward5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Forward5
     *
     * @param forward5 the value for T_VD_Data_Hour.Forward5
     *
     * @mbggenerated
     */
    public void setForward5(Integer forward5) {
        this.forward5 = forward5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Reverse5
     *
     * @return the value of T_VD_Data_Hour.Reverse5
     *
     * @mbggenerated
     */
    public Integer getReverse5() {
        return reverse5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Reverse5
     *
     * @param reverse5 the value for T_VD_Data_Hour.Reverse5
     *
     * @mbggenerated
     */
    public void setReverse5(Integer reverse5) {
        this.reverse5 = reverse5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.Occupancy5
     *
     * @return the value of T_VD_Data_Hour.Occupancy5
     *
     * @mbggenerated
     */
    public Double getOccupancy5() {
        return occupancy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.Occupancy5
     *
     * @param occupancy5 the value for T_VD_Data_Hour.Occupancy5
     *
     * @mbggenerated
     */
    public void setOccupancy5(Double occupancy5) {
        this.occupancy5 = occupancy5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.StatisticsCount
     *
     * @return the value of T_VD_Data_Hour.StatisticsCount
     *
     * @mbggenerated
     */
    public Integer getStatisticscount() {
        return statisticscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.StatisticsCount
     *
     * @param statisticscount the value for T_VD_Data_Hour.StatisticsCount
     *
     * @mbggenerated
     */
    public void setStatisticscount(Integer statisticscount) {
        this.statisticscount = statisticscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.GatherDate
     *
     * @return the value of T_VD_Data_Hour.GatherDate
     *
     * @mbggenerated
     */
    public Date getGatherdate() {
        return gatherdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.GatherDate
     *
     * @param gatherdate the value for T_VD_Data_Hour.GatherDate
     *
     * @mbggenerated
     */
    public void setGatherdate(Date gatherdate) {
        this.gatherdate = gatherdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.GatherTime
     *
     * @return the value of T_VD_Data_Hour.GatherTime
     *
     * @mbggenerated
     */
    public Date getGathertime() {
        return gathertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.GatherTime
     *
     * @param gathertime the value for T_VD_Data_Hour.GatherTime
     *
     * @mbggenerated
     */
    public void setGathertime(Date gathertime) {
        this.gathertime = gathertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.CreateDate
     *
     * @return the value of T_VD_Data_Hour.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.CreateDate
     *
     * @param createdate the value for T_VD_Data_Hour.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VD_Data_Hour.CreateTime
     *
     * @return the value of T_VD_Data_Hour.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VD_Data_Hour.CreateTime
     *
     * @param createtime the value for T_VD_Data_Hour.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TVDDataHour other = (TVDDataHour) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEquipid() == null ? other.getEquipid() == null : this.getEquipid().equals(other.getEquipid()))
            && (this.getAvgspd1() == null ? other.getAvgspd1() == null : this.getAvgspd1().equals(other.getAvgspd1()))
            && (this.getForward1() == null ? other.getForward1() == null : this.getForward1().equals(other.getForward1()))
            && (this.getReverse1() == null ? other.getReverse1() == null : this.getReverse1().equals(other.getReverse1()))
            && (this.getOccupancy1() == null ? other.getOccupancy1() == null : this.getOccupancy1().equals(other.getOccupancy1()))
            && (this.getAvgspd2() == null ? other.getAvgspd2() == null : this.getAvgspd2().equals(other.getAvgspd2()))
            && (this.getForward2() == null ? other.getForward2() == null : this.getForward2().equals(other.getForward2()))
            && (this.getReverse2() == null ? other.getReverse2() == null : this.getReverse2().equals(other.getReverse2()))
            && (this.getOccupancy2() == null ? other.getOccupancy2() == null : this.getOccupancy2().equals(other.getOccupancy2()))
            && (this.getAvgspd3() == null ? other.getAvgspd3() == null : this.getAvgspd3().equals(other.getAvgspd3()))
            && (this.getForward3() == null ? other.getForward3() == null : this.getForward3().equals(other.getForward3()))
            && (this.getReverse3() == null ? other.getReverse3() == null : this.getReverse3().equals(other.getReverse3()))
            && (this.getOccupancy3() == null ? other.getOccupancy3() == null : this.getOccupancy3().equals(other.getOccupancy3()))
            && (this.getAvgspd4() == null ? other.getAvgspd4() == null : this.getAvgspd4().equals(other.getAvgspd4()))
            && (this.getForward4() == null ? other.getForward4() == null : this.getForward4().equals(other.getForward4()))
            && (this.getReverse4() == null ? other.getReverse4() == null : this.getReverse4().equals(other.getReverse4()))
            && (this.getOccupancy4() == null ? other.getOccupancy4() == null : this.getOccupancy4().equals(other.getOccupancy4()))
            && (this.getAvgspd5() == null ? other.getAvgspd5() == null : this.getAvgspd5().equals(other.getAvgspd5()))
            && (this.getForward5() == null ? other.getForward5() == null : this.getForward5().equals(other.getForward5()))
            && (this.getReverse5() == null ? other.getReverse5() == null : this.getReverse5().equals(other.getReverse5()))
            && (this.getOccupancy5() == null ? other.getOccupancy5() == null : this.getOccupancy5().equals(other.getOccupancy5()))
            && (this.getStatisticscount() == null ? other.getStatisticscount() == null : this.getStatisticscount().equals(other.getStatisticscount()))
            && (this.getGatherdate() == null ? other.getGatherdate() == null : this.getGatherdate().equals(other.getGatherdate()))
            && (this.getGathertime() == null ? other.getGathertime() == null : this.getGathertime().equals(other.getGathertime()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEquipid() == null) ? 0 : getEquipid().hashCode());
        result = prime * result + ((getAvgspd1() == null) ? 0 : getAvgspd1().hashCode());
        result = prime * result + ((getForward1() == null) ? 0 : getForward1().hashCode());
        result = prime * result + ((getReverse1() == null) ? 0 : getReverse1().hashCode());
        result = prime * result + ((getOccupancy1() == null) ? 0 : getOccupancy1().hashCode());
        result = prime * result + ((getAvgspd2() == null) ? 0 : getAvgspd2().hashCode());
        result = prime * result + ((getForward2() == null) ? 0 : getForward2().hashCode());
        result = prime * result + ((getReverse2() == null) ? 0 : getReverse2().hashCode());
        result = prime * result + ((getOccupancy2() == null) ? 0 : getOccupancy2().hashCode());
        result = prime * result + ((getAvgspd3() == null) ? 0 : getAvgspd3().hashCode());
        result = prime * result + ((getForward3() == null) ? 0 : getForward3().hashCode());
        result = prime * result + ((getReverse3() == null) ? 0 : getReverse3().hashCode());
        result = prime * result + ((getOccupancy3() == null) ? 0 : getOccupancy3().hashCode());
        result = prime * result + ((getAvgspd4() == null) ? 0 : getAvgspd4().hashCode());
        result = prime * result + ((getForward4() == null) ? 0 : getForward4().hashCode());
        result = prime * result + ((getReverse4() == null) ? 0 : getReverse4().hashCode());
        result = prime * result + ((getOccupancy4() == null) ? 0 : getOccupancy4().hashCode());
        result = prime * result + ((getAvgspd5() == null) ? 0 : getAvgspd5().hashCode());
        result = prime * result + ((getForward5() == null) ? 0 : getForward5().hashCode());
        result = prime * result + ((getReverse5() == null) ? 0 : getReverse5().hashCode());
        result = prime * result + ((getOccupancy5() == null) ? 0 : getOccupancy5().hashCode());
        result = prime * result + ((getStatisticscount() == null) ? 0 : getStatisticscount().hashCode());
        result = prime * result + ((getGatherdate() == null) ? 0 : getGatherdate().hashCode());
        result = prime * result + ((getGathertime() == null) ? 0 : getGathertime().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", equipid=").append(equipid);
        sb.append(", avgspd1=").append(avgspd1);
        sb.append(", forward1=").append(forward1);
        sb.append(", reverse1=").append(reverse1);
        sb.append(", occupancy1=").append(occupancy1);
        sb.append(", avgspd2=").append(avgspd2);
        sb.append(", forward2=").append(forward2);
        sb.append(", reverse2=").append(reverse2);
        sb.append(", occupancy2=").append(occupancy2);
        sb.append(", avgspd3=").append(avgspd3);
        sb.append(", forward3=").append(forward3);
        sb.append(", reverse3=").append(reverse3);
        sb.append(", occupancy3=").append(occupancy3);
        sb.append(", avgspd4=").append(avgspd4);
        sb.append(", forward4=").append(forward4);
        sb.append(", reverse4=").append(reverse4);
        sb.append(", occupancy4=").append(occupancy4);
        sb.append(", avgspd5=").append(avgspd5);
        sb.append(", forward5=").append(forward5);
        sb.append(", reverse5=").append(reverse5);
        sb.append(", occupancy5=").append(occupancy5);
        sb.append(", statisticscount=").append(statisticscount);
        sb.append(", gatherdate=").append(gatherdate);
        sb.append(", gathertime=").append(gathertime);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}