package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器报表
 * 
 * @author shenchanghui
 *
 */
public class TVDDataDayResult implements Serializable {
	private int forward;

	private String equipname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Day.EquipId
	 *
	 * @mbggenerated
	 */
	private String equipid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Day.GatherDate
	 *
	 * @mbggenerated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "yyyy/MM/dd", timezone = "GMT+8")
	private Date gatherdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Day.GatherTime
	 *
	 * @mbggenerated
	 */
	private Date gathertime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	public int getForward() {
		return forward;
	}

	public void setForward(int forward) {
		this.forward = forward;
	}

	public String getEquipname() {
		return equipname;
	}

	public void setEquipname(String equipname) {
		this.equipname = equipname;
	}

	public String getEquipid() {
		return equipid;
	}

	public void setEquipid(String equipid) {
		this.equipid = equipid;
	}

	public Date getGatherdate() {
		return gatherdate;
	}

	public void setGatherdate(Date gatherdate) {
		this.gatherdate = gatherdate;
	}

	public Date getGathertime() {
		return gathertime;
	}

	public void setGathertime(Date gathertime) {
		this.gathertime = gathertime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((equipid == null) ? 0 : equipid.hashCode());
		result = prime * result + ((equipname == null) ? 0 : equipname.hashCode());
		result = prime * result + forward;
		result = prime * result + ((gatherdate == null) ? 0 : gatherdate.hashCode());
		result = prime * result + ((gathertime == null) ? 0 : gathertime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TVDDataDayResult other = (TVDDataDayResult) obj;
		if (equipid == null) {
			if (other.equipid != null)
				return false;
		} else if (!equipid.equals(other.equipid))
			return false;
		if (equipname == null) {
			if (other.equipname != null)
				return false;
		} else if (!equipname.equals(other.equipname))
			return false;
		if (forward != other.forward)
			return false;
		if (gatherdate == null) {
			if (other.gatherdate != null)
				return false;
		} else if (!gatherdate.equals(other.gatherdate))
			return false;
		if (gathertime == null) {
			if (other.gathertime != null)
				return false;
		} else if (!gathertime.equals(other.gathertime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TVDDataDayResult [forward=" + forward + ", equipname=" + equipname + ", equipid=" + equipid
				+ ", gatherdate=" + gatherdate + ", gathertime=" + gathertime + "]";
	}

}