package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 * 
 * @author shenchanghui
 *
 */
public class TVDDataHourResult implements Serializable {

	public TVDDataHourResult() {
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.EquipId
	 *
	 * @mbggenerated
	 */
	private String equipid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.AvgSpd1
	 *
	 * @mbggenerated
	 */
	private Double avgspd1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Forward1
	 *
	 * @mbggenerated
	 */
	private Integer forward1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Reverse1
	 *
	 * @mbggenerated
	 */
	private Integer reverse1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Occupancy1
	 *
	 * @mbggenerated
	 */
	private Double occupancy1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.AvgSpd2
	 *
	 * @mbggenerated
	 */
	private Double avgspd2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Forward2
	 *
	 * @mbggenerated
	 */
	private Integer forward2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Reverse2
	 *
	 * @mbggenerated
	 */
	private Integer reverse2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Occupancy2
	 *
	 * @mbggenerated
	 */
	private Double occupancy2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.AvgSpd3
	 *
	 * @mbggenerated
	 */
	private Double avgspd3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Forward3
	 *
	 * @mbggenerated
	 */
	private Integer forward3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Reverse3
	 *
	 * @mbggenerated
	 */
	private Integer reverse3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Occupancy3
	 *
	 * @mbggenerated
	 */
	private Double occupancy3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.AvgSpd4
	 *
	 * @mbggenerated
	 */
	private Double avgspd4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Forward4
	 *
	 * @mbggenerated
	 */
	private Integer forward4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Reverse4
	 *
	 * @mbggenerated
	 */
	private Integer reverse4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Occupancy4
	 *
	 * @mbggenerated
	 */
	private Double occupancy4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.AvgSpd5
	 *
	 * @mbggenerated
	 */
	private Double avgspd5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Forward5
	 *
	 * @mbggenerated
	 */
	private Integer forward5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Reverse5
	 *
	 * @mbggenerated
	 */
	private Integer reverse5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.Occupancy5
	 *
	 * @mbggenerated
	 */
	private Double occupancy5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.StatisticsCount
	 *
	 * @mbggenerated
	 */
	private Integer statisticscount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.GatherDate
	 *
	 * @mbggenerated
	 */
	private Date gatherdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.GatherTime
	 *
	 * @mbggenerated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "HH", timezone = "GMT+8")
	private Date gathertime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.CreateDate
	 *
	 * @mbggenerated
	 */
	private Date createdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.CreateTime
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table T_VD_Data_Hour
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private String equipname;
	private String controllerid;
	private int equiptype;
	private int channel;
	private String controllername;
	private String connectname;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEquipid() {
		return equipid;
	}

	public void setEquipid(String equipid) {
		this.equipid = equipid;
	}

	public Double getAvgspd1() {
		return avgspd1;
	}

	public void setAvgspd1(Double avgspd1) {
		this.avgspd1 = avgspd1;
	}

	public Integer getForward1() {
		return forward1;
	}

	public void setForward1(Integer forward1) {
		this.forward1 = forward1;
	}

	public Integer getReverse1() {
		return reverse1;
	}

	public void setReverse1(Integer reverse1) {
		this.reverse1 = reverse1;
	}

	public Double getOccupancy1() {
		return occupancy1;
	}

	public void setOccupancy1(Double occupancy1) {
		this.occupancy1 = occupancy1;
	}

	public Double getAvgspd2() {
		return avgspd2;
	}

	public void setAvgspd2(Double avgspd2) {
		this.avgspd2 = avgspd2;
	}

	public Integer getForward2() {
		return forward2;
	}

	public void setForward2(Integer forward2) {
		this.forward2 = forward2;
	}

	public Integer getReverse2() {
		return reverse2;
	}

	public void setReverse2(Integer reverse2) {
		this.reverse2 = reverse2;
	}

	public Double getOccupancy2() {
		return occupancy2;
	}

	public void setOccupancy2(Double occupancy2) {
		this.occupancy2 = occupancy2;
	}

	public Double getAvgspd3() {
		return avgspd3;
	}

	public void setAvgspd3(Double avgspd3) {
		this.avgspd3 = avgspd3;
	}

	public Integer getForward3() {
		return forward3;
	}

	public void setForward3(Integer forward3) {
		this.forward3 = forward3;
	}

	public Integer getReverse3() {
		return reverse3;
	}

	public void setReverse3(Integer reverse3) {
		this.reverse3 = reverse3;
	}

	public Double getOccupancy3() {
		return occupancy3;
	}

	public void setOccupancy3(Double occupancy3) {
		this.occupancy3 = occupancy3;
	}

	public Double getAvgspd4() {
		return avgspd4;
	}

	public void setAvgspd4(Double avgspd4) {
		this.avgspd4 = avgspd4;
	}

	public Integer getForward4() {
		return forward4;
	}

	public void setForward4(Integer forward4) {
		this.forward4 = forward4;
	}

	public Integer getReverse4() {
		return reverse4;
	}

	public void setReverse4(Integer reverse4) {
		this.reverse4 = reverse4;
	}

	public Double getOccupancy4() {
		return occupancy4;
	}

	public void setOccupancy4(Double occupancy4) {
		this.occupancy4 = occupancy4;
	}

	public Double getAvgspd5() {
		return avgspd5;
	}

	public void setAvgspd5(Double avgspd5) {
		this.avgspd5 = avgspd5;
	}

	public Integer getForward5() {
		return forward5;
	}

	public void setForward5(Integer forward5) {
		this.forward5 = forward5;
	}

	public Integer getReverse5() {
		return reverse5;
	}

	public void setReverse5(Integer reverse5) {
		this.reverse5 = reverse5;
	}

	public Double getOccupancy5() {
		return occupancy5;
	}

	public void setOccupancy5(Double occupancy5) {
		this.occupancy5 = occupancy5;
	}

	public Integer getStatisticscount() {
		return statisticscount;
	}

	public void setStatisticscount(Integer statisticscount) {
		this.statisticscount = statisticscount;
	}

	public Date getGatherdate() {
		return gatherdate;
	}

	public void setGatherdate(Date gatherdate) {
		this.gatherdate = gatherdate;
	}

	public Date getGathertime() {
		return gathertime;
	}

	public void setGathertime(Date gathertime) {
		this.gathertime = gathertime;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getEquipname() {
		return equipname;
	}

	public void setEquipname(String equipname) {
		this.equipname = equipname;
	}

	public String getControllerid() {
		return controllerid;
	}

	public void setControllerid(String controllerid) {
		this.controllerid = controllerid;
	}

	public int getEquiptype() {
		return equiptype;
	}

	public void setEquiptype(int equiptype) {
		this.equiptype = equiptype;
	}

	public int getChannel() {
		return channel;
	}

	public void setChannel(int channel) {
		this.channel = channel;
	}

	public String getControllername() {
		return controllername;
	}

	public void setControllername(String controllername) {
		this.controllername = controllername;
	}

	public String getConnectname() {
		return connectname;
	}

	public void setConnectname(String connectname) {
		this.connectname = connectname;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((avgspd1 == null) ? 0 : avgspd1.hashCode());
		result = prime * result + ((avgspd2 == null) ? 0 : avgspd2.hashCode());
		result = prime * result + ((avgspd3 == null) ? 0 : avgspd3.hashCode());
		result = prime * result + ((avgspd4 == null) ? 0 : avgspd4.hashCode());
		result = prime * result + ((avgspd5 == null) ? 0 : avgspd5.hashCode());
		result = prime * result + channel;
		result = prime * result + ((connectname == null) ? 0 : connectname.hashCode());
		result = prime * result + ((controllerid == null) ? 0 : controllerid.hashCode());
		result = prime * result + ((controllername == null) ? 0 : controllername.hashCode());
		result = prime * result + ((createdate == null) ? 0 : createdate.hashCode());
		result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
		result = prime * result + ((equipid == null) ? 0 : equipid.hashCode());
		result = prime * result + ((equipname == null) ? 0 : equipname.hashCode());
		result = prime * result + equiptype;
		result = prime * result + ((forward1 == null) ? 0 : forward1.hashCode());
		result = prime * result + ((forward2 == null) ? 0 : forward2.hashCode());
		result = prime * result + ((forward3 == null) ? 0 : forward3.hashCode());
		result = prime * result + ((forward4 == null) ? 0 : forward4.hashCode());
		result = prime * result + ((forward5 == null) ? 0 : forward5.hashCode());
		result = prime * result + ((gatherdate == null) ? 0 : gatherdate.hashCode());
		result = prime * result + ((gathertime == null) ? 0 : gathertime.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((occupancy1 == null) ? 0 : occupancy1.hashCode());
		result = prime * result + ((occupancy2 == null) ? 0 : occupancy2.hashCode());
		result = prime * result + ((occupancy3 == null) ? 0 : occupancy3.hashCode());
		result = prime * result + ((occupancy4 == null) ? 0 : occupancy4.hashCode());
		result = prime * result + ((occupancy5 == null) ? 0 : occupancy5.hashCode());
		result = prime * result + ((reverse1 == null) ? 0 : reverse1.hashCode());
		result = prime * result + ((reverse2 == null) ? 0 : reverse2.hashCode());
		result = prime * result + ((reverse3 == null) ? 0 : reverse3.hashCode());
		result = prime * result + ((reverse4 == null) ? 0 : reverse4.hashCode());
		result = prime * result + ((reverse5 == null) ? 0 : reverse5.hashCode());
		result = prime * result + ((statisticscount == null) ? 0 : statisticscount.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TVDDataHourResult other = (TVDDataHourResult) obj;
		if (avgspd1 == null) {
			if (other.avgspd1 != null)
				return false;
		} else if (!avgspd1.equals(other.avgspd1))
			return false;
		if (avgspd2 == null) {
			if (other.avgspd2 != null)
				return false;
		} else if (!avgspd2.equals(other.avgspd2))
			return false;
		if (avgspd3 == null) {
			if (other.avgspd3 != null)
				return false;
		} else if (!avgspd3.equals(other.avgspd3))
			return false;
		if (avgspd4 == null) {
			if (other.avgspd4 != null)
				return false;
		} else if (!avgspd4.equals(other.avgspd4))
			return false;
		if (avgspd5 == null) {
			if (other.avgspd5 != null)
				return false;
		} else if (!avgspd5.equals(other.avgspd5))
			return false;
		if (channel != other.channel)
			return false;
		if (connectname == null) {
			if (other.connectname != null)
				return false;
		} else if (!connectname.equals(other.connectname))
			return false;
		if (controllerid == null) {
			if (other.controllerid != null)
				return false;
		} else if (!controllerid.equals(other.controllerid))
			return false;
		if (controllername == null) {
			if (other.controllername != null)
				return false;
		} else if (!controllername.equals(other.controllername))
			return false;
		if (createdate == null) {
			if (other.createdate != null)
				return false;
		} else if (!createdate.equals(other.createdate))
			return false;
		if (createtime == null) {
			if (other.createtime != null)
				return false;
		} else if (!createtime.equals(other.createtime))
			return false;
		if (equipid == null) {
			if (other.equipid != null)
				return false;
		} else if (!equipid.equals(other.equipid))
			return false;
		if (equipname == null) {
			if (other.equipname != null)
				return false;
		} else if (!equipname.equals(other.equipname))
			return false;
		if (equiptype != other.equiptype)
			return false;
		if (forward1 == null) {
			if (other.forward1 != null)
				return false;
		} else if (!forward1.equals(other.forward1))
			return false;
		if (forward2 == null) {
			if (other.forward2 != null)
				return false;
		} else if (!forward2.equals(other.forward2))
			return false;
		if (forward3 == null) {
			if (other.forward3 != null)
				return false;
		} else if (!forward3.equals(other.forward3))
			return false;
		if (forward4 == null) {
			if (other.forward4 != null)
				return false;
		} else if (!forward4.equals(other.forward4))
			return false;
		if (forward5 == null) {
			if (other.forward5 != null)
				return false;
		} else if (!forward5.equals(other.forward5))
			return false;
		if (gatherdate == null) {
			if (other.gatherdate != null)
				return false;
		} else if (!gatherdate.equals(other.gatherdate))
			return false;
		if (gathertime == null) {
			if (other.gathertime != null)
				return false;
		} else if (!gathertime.equals(other.gathertime))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (occupancy1 == null) {
			if (other.occupancy1 != null)
				return false;
		} else if (!occupancy1.equals(other.occupancy1))
			return false;
		if (occupancy2 == null) {
			if (other.occupancy2 != null)
				return false;
		} else if (!occupancy2.equals(other.occupancy2))
			return false;
		if (occupancy3 == null) {
			if (other.occupancy3 != null)
				return false;
		} else if (!occupancy3.equals(other.occupancy3))
			return false;
		if (occupancy4 == null) {
			if (other.occupancy4 != null)
				return false;
		} else if (!occupancy4.equals(other.occupancy4))
			return false;
		if (occupancy5 == null) {
			if (other.occupancy5 != null)
				return false;
		} else if (!occupancy5.equals(other.occupancy5))
			return false;
		if (reverse1 == null) {
			if (other.reverse1 != null)
				return false;
		} else if (!reverse1.equals(other.reverse1))
			return false;
		if (reverse2 == null) {
			if (other.reverse2 != null)
				return false;
		} else if (!reverse2.equals(other.reverse2))
			return false;
		if (reverse3 == null) {
			if (other.reverse3 != null)
				return false;
		} else if (!reverse3.equals(other.reverse3))
			return false;
		if (reverse4 == null) {
			if (other.reverse4 != null)
				return false;
		} else if (!reverse4.equals(other.reverse4))
			return false;
		if (reverse5 == null) {
			if (other.reverse5 != null)
				return false;
		} else if (!reverse5.equals(other.reverse5))
			return false;
		if (statisticscount == null) {
			if (other.statisticscount != null)
				return false;
		} else if (!statisticscount.equals(other.statisticscount))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TVDDataHourResult [id=" + id + ", equipid=" + equipid + ", avgspd1=" + avgspd1 + ", forward1="
				+ forward1 + ", reverse1=" + reverse1 + ", occupancy1=" + occupancy1 + ", avgspd2=" + avgspd2
				+ ", forward2=" + forward2 + ", reverse2=" + reverse2 + ", occupancy2=" + occupancy2 + ", avgspd3="
				+ avgspd3 + ", forward3=" + forward3 + ", reverse3=" + reverse3 + ", occupancy3=" + occupancy3
				+ ", avgspd4=" + avgspd4 + ", forward4=" + forward4 + ", reverse4=" + reverse4 + ", occupancy4="
				+ occupancy4 + ", avgspd5=" + avgspd5 + ", forward5=" + forward5 + ", reverse5=" + reverse5
				+ ", occupancy5=" + occupancy5 + ", statisticscount=" + statisticscount + ", gatherdate=" + gatherdate
				+ ", gathertime=" + gathertime + ", createdate=" + createdate + ", createtime=" + createtime
				+ ", equipname=" + equipname + ", controllerid=" + controllerid + ", equiptype=" + equiptype
				+ ", channel=" + channel + ", controllername=" + controllername + ", connectname=" + connectname + "]";
	}

}