package com.mgskj.model;

import java.io.Serializable;
import java.util.Date;

public class UserName implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.EmployeeId
     *
     * @mbggenerated
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.RealName
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.IsForbidden
     *
     * @mbggenerated
     */
    private Boolean isforbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.ForbidReason
     *
     * @mbggenerated
     */
    private String forbidreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.IsDeleted
     *
     * @mbggenerated
     */
    private Boolean isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_UserInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    private byte[] concurrencytoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_UserInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.Id
     *
     * @return the value of T_UserInfo.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.Id
     *
     * @param id the value for T_UserInfo.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.EmployeeId
     *
     * @return the value of T_UserInfo.EmployeeId
     *
     * @mbggenerated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.EmployeeId
     *
     * @param employeeid the value for T_UserInfo.EmployeeId
     *
     * @mbggenerated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.Password
     *
     * @return the value of T_UserInfo.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.Password
     *
     * @param password the value for T_UserInfo.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.RealName
     *
     * @return the value of T_UserInfo.RealName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.RealName
     *
     * @param realname the value for T_UserInfo.RealName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.Description
     *
     * @return the value of T_UserInfo.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.Description
     *
     * @param description the value for T_UserInfo.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.IsForbidden
     *
     * @return the value of T_UserInfo.IsForbidden
     *
     * @mbggenerated
     */
    public Boolean getIsforbidden() {
        return isforbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.IsForbidden
     *
     * @param isforbidden the value for T_UserInfo.IsForbidden
     *
     * @mbggenerated
     */
    public void setIsforbidden(Boolean isforbidden) {
        this.isforbidden = isforbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.ForbidReason
     *
     * @return the value of T_UserInfo.ForbidReason
     *
     * @mbggenerated
     */
    public String getForbidreason() {
        return forbidreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.ForbidReason
     *
     * @param forbidreason the value for T_UserInfo.ForbidReason
     *
     * @mbggenerated
     */
    public void setForbidreason(String forbidreason) {
        this.forbidreason = forbidreason == null ? null : forbidreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.IsDeleted
     *
     * @return the value of T_UserInfo.IsDeleted
     *
     * @mbggenerated
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.IsDeleted
     *
     * @param isdeleted the value for T_UserInfo.IsDeleted
     *
     * @mbggenerated
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.CreateDate
     *
     * @return the value of T_UserInfo.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.CreateDate
     *
     * @param createdate the value for T_UserInfo.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.CreateTime
     *
     * @return the value of T_UserInfo.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.CreateTime
     *
     * @param createtime the value for T_UserInfo.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_UserInfo.ConcurrencyToken
     *
     * @return the value of T_UserInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    public byte[] getConcurrencytoken() {
        return concurrencytoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_UserInfo.ConcurrencyToken
     *
     * @param concurrencytoken the value for T_UserInfo.ConcurrencyToken
     *
     * @mbggenerated
     */
    public void setConcurrencytoken(byte[] concurrencytoken) {
        this.concurrencytoken = concurrencytoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_UserInfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserName other = (UserName) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIsforbidden() == null ? other.getIsforbidden() == null : this.getIsforbidden().equals(other.getIsforbidden()))
            && (this.getForbidreason() == null ? other.getForbidreason() == null : this.getForbidreason().equals(other.getForbidreason()))
            && (this.getIsdeleted() == null ? other.getIsdeleted() == null : this.getIsdeleted().equals(other.getIsdeleted()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getConcurrencytoken() == null ? other.getConcurrencytoken() == null : this.getConcurrencytoken().equals(other.getConcurrencytoken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_UserInfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIsforbidden() == null) ? 0 : getIsforbidden().hashCode());
        result = prime * result + ((getForbidreason() == null) ? 0 : getForbidreason().hashCode());
        result = prime * result + ((getIsdeleted() == null) ? 0 : getIsdeleted().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getConcurrencytoken() == null) ? 0 : getConcurrencytoken().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_UserInfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", password=").append(password);
        sb.append(", realname=").append(realname);
        sb.append(", description=").append(description);
        sb.append(", isforbidden=").append(isforbidden);
        sb.append(", forbidreason=").append(forbidreason);
        sb.append(", isdeleted=").append(isdeleted);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", concurrencytoken=").append(concurrencytoken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}