package com.mgskj.bean;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 *
 * @author shenchanghui
 */
public class BoardOperationResult implements Serializable {

    public BoardOperationResult() {
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private String equipname;
    private String routecode;
    private String mile;
    private String businesscategory;
    private String regionname;
    private String fontname;
    private String fontsize;
    private int fontcolor;
    private String fontcolordesc;
    private String description;
    private String username;
    private int result;
    private String resultdesc;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String operatetime;

    public String getEquipname() {
        return equipname;
    }

    public void setEquipname(String equipname) {
        this.equipname = equipname;
    }

    public String getRoutecode() {
        return routecode;
    }

    public void setRoutecode(String routecode) {
        this.routecode = routecode;
    }

    public String getMile() {
        return mile;
    }

    public void setMile(String mile) {
        this.mile = mile;
    }

    public String getBusinesscategory() {
        return businesscategory;
    }

    public void setBusinesscategory(String businesscategory) {
        this.businesscategory = businesscategory;
    }

    public String getRegionname() {
        return regionname;
    }

    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    public String getFontname() {
        return fontname;
    }

    public void setFontname(String fontname) {
        this.fontname = fontname;
    }

    public String getFontsize() {
        return fontsize;
    }

    public void setFontsize(String fontsize) {
        this.fontsize = fontsize;
    }

    public int getFontcolor() {
        return fontcolor;
    }

    public void setFontcolor(int fontcolor) {
        this.fontcolor = fontcolor;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public String getOperatetime() {
        return operatetime;
    }

    public void setOperatetime(String operatetime) {
        this.operatetime = operatetime;
    }

    public String getResultdesc() {
        return resultdesc;
    }

    public void setResultdesc(String resultdesc) {
        this.resultdesc = resultdesc;
    }

    public String getFontcolordesc() {
        return fontcolordesc;
    }

    public void setFontcolordesc(String fontcolordesc) {
        this.fontcolordesc = fontcolordesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BoardOperationResult that = (BoardOperationResult) o;
        return fontcolor == that.fontcolor &&
                result == that.result &&
                Objects.equals(equipname, that.equipname) &&
                Objects.equals(routecode, that.routecode) &&
                Objects.equals(mile, that.mile) &&
                Objects.equals(businesscategory, that.businesscategory) &&
                Objects.equals(regionname, that.regionname) &&
                Objects.equals(fontname, that.fontname) &&
                Objects.equals(fontsize, that.fontsize) &&
                Objects.equals(fontcolordesc, that.fontcolordesc) &&
                Objects.equals(description, that.description) &&
                Objects.equals(username, that.username) &&
                Objects.equals(resultdesc, that.resultdesc) &&
                Objects.equals(operatetime, that.operatetime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(equipname, routecode, mile, businesscategory, regionname, fontname, fontsize, fontcolor, fontcolordesc, description, username, result, resultdesc, operatetime);
    }

    @Override
    public String toString() {
        return "BoardOperationResult{" +
                "equipname='" + equipname + '\'' +
                ", routecode='" + routecode + '\'' +
                ", mile='" + mile + '\'' +
                ", businesscategory='" + businesscategory + '\'' +
                ", regionname='" + regionname + '\'' +
                ", fontname='" + fontname + '\'' +
                ", fontsize='" + fontsize + '\'' +
                ", fontcolor=" + fontcolor +
                ", fontcolordesc='" + fontcolordesc + '\'' +
                ", description='" + description + '\'' +
                ", username='" + username + '\'' +
                ", result=" + result +
                ", resultdesc='" + resultdesc + '\'' +
                ", operatetime='" + operatetime + '\'' +
                '}';
    }
}