package com.mgskj.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 * 
 * @author shenchanghui
 *
 */
public class ETEquipResult implements Serializable {

	public ETEquipResult() {
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table T_VD_Data_Hour
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private String id;
	private String regionname;
	private String regionid;
	private String routecode;
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date createdate;
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
	private Date createtime;
	private int equiptype;
	private String equiptypedesc;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRegionname() {
		return regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	public String getRegionid() {
		return regionid;
	}

	public void setRegionid(String regionid) {
		this.regionid = regionid;
	}

	public String getRoutecode() {
		return routecode;
	}

	public void setRoutecode(String routecode) {
		this.routecode = routecode;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public int getEquiptype() {
		return equiptype;
	}

	public void setEquiptype(int equiptype) {
		this.equiptype = equiptype;
	}

	public String getEquiptypedesc() {
		return equiptypedesc;
	}

	public void setEquiptypedesc(String equiptypedesc) {
		this.equiptypedesc = equiptypedesc;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createdate == null) ? 0 : createdate.hashCode());
		result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
		result = prime * result + equiptype;
		result = prime * result + ((equiptypedesc == null) ? 0 : equiptypedesc.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((regionid == null) ? 0 : regionid.hashCode());
		result = prime * result + ((regionname == null) ? 0 : regionname.hashCode());
		result = prime * result + ((routecode == null) ? 0 : routecode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ETEquipResult other = (ETEquipResult) obj;
		if (createdate == null) {
			if (other.createdate != null)
				return false;
		} else if (!createdate.equals(other.createdate))
			return false;
		if (createtime == null) {
			if (other.createtime != null)
				return false;
		} else if (!createtime.equals(other.createtime))
			return false;
		if (equiptype != other.equiptype)
			return false;
		if (equiptypedesc == null) {
			if (other.equiptypedesc != null)
				return false;
		} else if (!equiptypedesc.equals(other.equiptypedesc))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (regionid == null) {
			if (other.regionid != null)
				return false;
		} else if (!regionid.equals(other.regionid))
			return false;
		if (regionname == null) {
			if (other.regionname != null)
				return false;
		} else if (!regionname.equals(other.regionname))
			return false;
		if (routecode == null) {
			if (other.routecode != null)
				return false;
		} else if (!routecode.equals(other.routecode))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ETEquipResult [id=" + id + ", regionname=" + regionname + ", regionid=" + regionid + ", routecode="
				+ routecode + ", createdate=" + createdate + ", createtime=" + createtime + ", equiptype=" + equiptype
				+ ", equiptypedesc=" + equiptypedesc + "]";
	}

}