package com.mgskj.bean;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 *
 * @author shenchanghui
 */
public class ETOperationResult implements Serializable {

    public ETOperationResult() {
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private int equiptype;
    private String equiptypedesc;
    private String equipname;
    private String routecode;
    private String mile;
    private String regionname;
    private String dealingstatus;
    private int duplicatecount;
    private String username;
    private int operation;
    private String operationdesc;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String operatetime;

    public int getEquiptype() {
        return equiptype;
    }

    public void setEquiptype(int equiptype) {
        this.equiptype = equiptype;
    }

    public String getEquipname() {
        return equipname;
    }

    public void setEquipname(String equipname) {
        this.equipname = equipname;
    }

    public String getRoutecode() {
        return routecode;
    }

    public void setRoutecode(String routecode) {
        this.routecode = routecode;
    }

    public String getMile() {
        return mile;
    }

    public void setMile(String mile) {
        this.mile = mile;
    }

    public String getRegionname() {
        return regionname;
    }

    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    public String getDealingstatus() {
        return dealingstatus;
    }

    public void setDealingstatus(String dealingstatus) {
        this.dealingstatus = dealingstatus;
    }

    public int getDuplicatecount() {
        return duplicatecount;
    }

    public void setDuplicatecount(int duplicatecount) {
        this.duplicatecount = duplicatecount;
    }

    public String getOperatetime() {
        return operatetime;
    }

    public void setOperatetime(String operatetime) {
        this.operatetime = operatetime;
    }


    public String getEquiptypedesc() {
        return equiptypedesc;
    }

    public void setEquiptypedesc(String equiptypedesc) {
        this.equiptypedesc = equiptypedesc;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getOperation() {
        return operation;
    }

    public void setOperation(int operation) {
        this.operation = operation;
    }

    public String getOperationdesc() {
        return operationdesc;
    }

    public void setOperationdesc(String operationdesc) {
        this.operationdesc = operationdesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ETOperationResult that = (ETOperationResult) o;
        return equiptype == that.equiptype &&
                duplicatecount == that.duplicatecount &&
                operation == that.operation &&
                Objects.equals(equiptypedesc, that.equiptypedesc) &&
                Objects.equals(equipname, that.equipname) &&
                Objects.equals(routecode, that.routecode) &&
                Objects.equals(mile, that.mile) &&
                Objects.equals(regionname, that.regionname) &&
                Objects.equals(dealingstatus, that.dealingstatus) &&
                Objects.equals(username, that.username) &&
                Objects.equals(operationdesc, that.operationdesc) &&
                Objects.equals(operatetime, that.operatetime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(equiptype, equiptypedesc, equipname, routecode, mile, regionname, dealingstatus, duplicatecount, username, operation, operationdesc, operatetime);
    }

    @Override
    public String toString() {
        return "ETOperationResult{" +
                "equiptype=" + equiptype +
                ", equiptypedesc='" + equiptypedesc + '\'' +
                ", equipname='" + equipname + '\'' +
                ", routecode='" + routecode + '\'' +
                ", mile='" + mile + '\'' +
                ", regionname='" + regionname + '\'' +
                ", dealingstatus='" + dealingstatus + '\'' +
                ", duplicatecount=" + duplicatecount +
                ", username='" + username + '\'' +
                ", operation=" + operation +
                ", operationdesc='" + operationdesc + '\'' +
                ", operatetime='" + operatetime + '\'' +
                '}';
    }
}