package com.mgskj.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 *
 * @author shenchanghui
 */
public class EVDOperationResult implements Serializable {

    public EVDOperationResult() {
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private int equiptype;
    private String equiptypedesc;
    private String equipname;
    private String routecode;
    private String mile;
    private String regionname;
    private String username;
    private int operation;
    private String operationdesc;
    private int duplicatecount;
    private String dealingstatus;
    private int result;
    private String resultdesc;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date createdate;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
    private Date createtime;

    public int getEquiptype() {
        return equiptype;
    }

    public void setEquiptype(int equiptype) {
        this.equiptype = equiptype;
    }

    public String getEquipname() {
        return equipname;
    }

    public void setEquipname(String equipname) {
        this.equipname = equipname;
    }

    public String getRoutecode() {
        return routecode;
    }

    public void setRoutecode(String routecode) {
        this.routecode = routecode;
    }

    public String getMile() {
        return mile;
    }

    public void setMile(String mile) {
        this.mile = mile;
    }

    public String getRegionname() {
        return regionname;
    }

    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getOperation() {
        return operation;
    }

    public void setOperation(int operation) {
        this.operation = operation;
    }

    public int getDuplicatecount() {
        return duplicatecount;
    }

    public void setDuplicatecount(int duplicatecount) {
        this.duplicatecount = duplicatecount;
    }

    public String getDealingstatus() {
        return dealingstatus;
    }

    public void setDealingstatus(String dealingstatus) {
        this.dealingstatus = dealingstatus;
    }

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getOperationdesc() {
        return operationdesc;
    }

    public void setOperationdesc(String operationdesc) {
        this.operationdesc = operationdesc;
    }

    public String getResultdesc() {
        return resultdesc;
    }

    public void setResultdesc(String resultdesc) {
        this.resultdesc = resultdesc;
    }

    public String getEquiptypedesc() {
        return equiptypedesc;
    }

    public void setEquiptypedesc(String equiptypedesc) {
        this.equiptypedesc = equiptypedesc;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((createdate == null) ? 0 : createdate.hashCode());
        result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
        result = prime * result + ((dealingstatus == null) ? 0 : dealingstatus.hashCode());
        result = prime * result + duplicatecount;
        result = prime * result + ((equipname == null) ? 0 : equipname.hashCode());
        result = prime * result + equiptype;
        result = prime * result + ((equiptypedesc == null) ? 0 : equiptypedesc.hashCode());
        result = prime * result + ((mile == null) ? 0 : mile.hashCode());
        result = prime * result + operation;
        result = prime * result + ((operationdesc == null) ? 0 : operationdesc.hashCode());
        result = prime * result + ((regionname == null) ? 0 : regionname.hashCode());
        result = prime * result + this.result;
        result = prime * result + ((resultdesc == null) ? 0 : resultdesc.hashCode());
        result = prime * result + ((routecode == null) ? 0 : routecode.hashCode());
        result = prime * result + ((username == null) ? 0 : username.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EVDOperationResult other = (EVDOperationResult) obj;
        if (createdate == null) {
            if (other.createdate != null)
                return false;
        } else if (!createdate.equals(other.createdate))
            return false;
        if (createtime == null) {
            if (other.createtime != null)
                return false;
        } else if (!createtime.equals(other.createtime))
            return false;
        if (dealingstatus == null) {
            if (other.dealingstatus != null)
                return false;
        } else if (!dealingstatus.equals(other.dealingstatus))
            return false;
        if (duplicatecount != other.duplicatecount)
            return false;
        if (equipname == null) {
            if (other.equipname != null)
                return false;
        } else if (!equipname.equals(other.equipname))
            return false;
        if (equiptype != other.equiptype)
            return false;
        if (equiptypedesc == null) {
            if (other.equiptypedesc != null)
                return false;
        } else if (!equiptypedesc.equals(other.equiptypedesc))
            return false;
        if (mile == null) {
            if (other.mile != null)
                return false;
        } else if (!mile.equals(other.mile))
            return false;
        if (operation != other.operation)
            return false;
        if (operationdesc == null) {
            if (other.operationdesc != null)
                return false;
        } else if (!operationdesc.equals(other.operationdesc))
            return false;
        if (regionname == null) {
            if (other.regionname != null)
                return false;
        } else if (!regionname.equals(other.regionname))
            return false;
        if (result != other.result)
            return false;
        if (resultdesc == null) {
            if (other.resultdesc != null)
                return false;
        } else if (!resultdesc.equals(other.resultdesc))
            return false;
        if (routecode == null) {
            if (other.routecode != null)
                return false;
        } else if (!routecode.equals(other.routecode))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        } else if (!username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "EVDOperationResult [equiptype=" + equiptype + ", equiptypedesc=" + equiptypedesc + ", equipname="
                + equipname + ", routecode=" + routecode + ", mile=" + mile + ", regionname=" + regionname
                + ", username=" + username + ", operation=" + operation + ", operationdesc=" + operationdesc
                + ", duplicatecount=" + duplicatecount + ", dealingstatus=" + dealingstatus + ", result=" + result
                + ", resultdesc=" + resultdesc + ", createdate=" + createdate + ", createtime=" + createtime + "]";
    }

}