package com.mgskj.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * 车检器
 *
 * @author shenchanghui
 */
public class FAOperationResult implements Serializable {

    public FAOperationResult() {
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private int equiptype;
    private String equiptypedesc;
    private String equipname;
    private String routecode;
    private String mile;
    private String regionname;
    private String username;
    private int operation = -2;
    private String operationdesc;
    private int duplicatecount;
    private String dealingstatus;
    private int result = -2;
    private String resultdesc;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date createdate;
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
    private Date createtime;

    public Date getFiredate() {
        return firedate;
    }

    public void setFiredate(Date firedate) {
        this.firedate = firedate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date firedate;

    public int getEquiptype() {
        return equiptype;
    }

    public void setEquiptype(int equiptype) {
        this.equiptype = equiptype;
    }

    public String getEquipname() {
        return equipname;
    }

    public void setEquipname(String equipname) {
        this.equipname = equipname;
    }

    public String getRoutecode() {
        return routecode;
    }

    public void setRoutecode(String routecode) {
        this.routecode = routecode;
    }

    public String getMile() {
        return mile;
    }

    public void setMile(String mile) {
        this.mile = mile;
    }

    public String getRegionname() {
        return regionname;
    }

    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getOperation() {
        return operation;
    }

    public void setOperation(int operation) {
        this.operation = operation;
    }

    public int getDuplicatecount() {
        return duplicatecount;
    }

    public void setDuplicatecount(int duplicatecount) {
        this.duplicatecount = duplicatecount;
    }

    public String getDealingstatus() {
        return dealingstatus;
    }

    public void setDealingstatus(String dealingstatus) {
        this.dealingstatus = dealingstatus;
    }

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getOperationdesc() {
        return operationdesc;
    }

    public void setOperationdesc(String operationdesc) {
        this.operationdesc = operationdesc;
    }

    public String getResultdesc() {
        return resultdesc;
    }

    public void setResultdesc(String resultdesc) {
        this.resultdesc = resultdesc;
    }

    public String getEquiptypedesc() {
        return equiptypedesc;
    }

    public void setEquiptypedesc(String equiptypedesc) {
        this.equiptypedesc = equiptypedesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FAOperationResult that = (FAOperationResult) o;
        return equiptype == that.equiptype &&
                operation == that.operation &&
                duplicatecount == that.duplicatecount &&
                result == that.result &&
                Objects.equals(equiptypedesc, that.equiptypedesc) &&
                Objects.equals(equipname, that.equipname) &&
                Objects.equals(routecode, that.routecode) &&
                Objects.equals(mile, that.mile) &&
                Objects.equals(regionname, that.regionname) &&
                Objects.equals(username, that.username) &&
                Objects.equals(operationdesc, that.operationdesc) &&
                Objects.equals(dealingstatus, that.dealingstatus) &&
                Objects.equals(resultdesc, that.resultdesc) &&
                Objects.equals(createdate, that.createdate) &&
                Objects.equals(createtime, that.createtime) &&
                Objects.equals(firedate, that.firedate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(equiptype, equiptypedesc, equipname, routecode, mile, regionname, username, operation, operationdesc, duplicatecount, dealingstatus, result, resultdesc, createdate, createtime, firedate);
    }

    @Override
    public String toString() {
        return "FAOperationResult{" +
                "equiptype=" + equiptype +
                ", equiptypedesc='" + equiptypedesc + '\'' +
                ", equipname='" + equipname + '\'' +
                ", routecode='" + routecode + '\'' +
                ", mile='" + mile + '\'' +
                ", regionname='" + regionname + '\'' +
                ", username='" + username + '\'' +
                ", operation=" + operation +
                ", operationdesc='" + operationdesc + '\'' +
                ", duplicatecount=" + duplicatecount +
                ", dealingstatus='" + dealingstatus + '\'' +
                ", result=" + result +
                ", resultdesc='" + resultdesc + '\'' +
                ", createdate=" + createdate +
                ", createtime=" + createtime +
                ", firedate=" + firedate +
                '}';
    }
}