package com.mgskj.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.io.Serializable;
import java.util.Date;

public class TOperationLogWResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.ParentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.EmployeeId
     *
     * @mbggenerated
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.SourceModule
     *
     * @mbggenerated
     */
    private Integer sourcemodule;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.Operation
     *
     * @mbggenerated
     */
    private Integer operation;

    private String operationdesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.Target
     *
     * @mbggenerated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.Result
     *
     * @mbggenerated
     */
    private Integer result;

    private String resultdesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.CreateDate
     *
     * @mbggenerated
     */
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_OperationLogW.CreateTime
     *
     * @mbggenerated
     */
    @Temporal(TemporalType.TIMESTAMP)
    @JsonFormat(pattern = "HH:mm:ss", timezone = "GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table T_OperationLogW
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.Id
     *
     * @return the value of T_OperationLogW.Id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.Id
     *
     * @param id the value for T_OperationLogW.Id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.ParentId
     *
     * @return the value of T_OperationLogW.ParentId
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.ParentId
     *
     * @param parentid the value for T_OperationLogW.ParentId
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.EmployeeId
     *
     * @return the value of T_OperationLogW.EmployeeId
     * @mbggenerated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.EmployeeId
     *
     * @param employeeid the value for T_OperationLogW.EmployeeId
     * @mbggenerated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.UserName
     *
     * @return the value of T_OperationLogW.UserName
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.UserName
     *
     * @param username the value for T_OperationLogW.UserName
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.SourceModule
     *
     * @return the value of T_OperationLogW.SourceModule
     * @mbggenerated
     */
    public Integer getSourcemodule() {
        return sourcemodule;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.SourceModule
     *
     * @param sourcemodule the value for T_OperationLogW.SourceModule
     * @mbggenerated
     */
    public void setSourcemodule(Integer sourcemodule) {
        this.sourcemodule = sourcemodule;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.Operation
     *
     * @return the value of T_OperationLogW.Operation
     * @mbggenerated
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.Operation
     *
     * @param operation the value for T_OperationLogW.Operation
     * @mbggenerated
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.Target
     *
     * @return the value of T_OperationLogW.Target
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.Target
     *
     * @param target the value for T_OperationLogW.Target
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.Description
     *
     * @return the value of T_OperationLogW.Description
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.Description
     *
     * @param description the value for T_OperationLogW.Description
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.Result
     *
     * @return the value of T_OperationLogW.Result
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.Result
     *
     * @param result the value for T_OperationLogW.Result
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.CreateDate
     *
     * @return the value of T_OperationLogW.CreateDate
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.CreateDate
     *
     * @param createdate the value for T_OperationLogW.CreateDate
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_OperationLogW.CreateTime
     *
     * @return the value of T_OperationLogW.CreateTime
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_OperationLogW.CreateTime
     *
     * @param createtime the value for T_OperationLogW.CreateTime
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getOperationdesc() {
        return operationdesc;
    }

    public void setOperationdesc(String operationdesc) {
        this.operationdesc = operationdesc;
    }

    public String getResultdesc() {
        return resultdesc;
    }

    public void setResultdesc(String resultdesc) {
        this.resultdesc = resultdesc;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((createdate == null) ? 0 : createdate.hashCode());
        result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        result = prime * result + ((employeeid == null) ? 0 : employeeid.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((operation == null) ? 0 : operation.hashCode());
        result = prime * result + ((operationdesc == null) ? 0 : operationdesc.hashCode());
        result = prime * result + ((parentid == null) ? 0 : parentid.hashCode());
        result = prime * result + ((this.result == null) ? 0 : this.result.hashCode());
        result = prime * result + ((resultdesc == null) ? 0 : resultdesc.hashCode());
        result = prime * result + ((sourcemodule == null) ? 0 : sourcemodule.hashCode());
        result = prime * result + ((target == null) ? 0 : target.hashCode());
        result = prime * result + ((username == null) ? 0 : username.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TOperationLogWResult other = (TOperationLogWResult) obj;
        if (createdate == null) {
            if (other.createdate != null)
                return false;
        } else if (!createdate.equals(other.createdate))
            return false;
        if (createtime == null) {
            if (other.createtime != null)
                return false;
        } else if (!createtime.equals(other.createtime))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        } else if (!description.equals(other.description))
            return false;
        if (employeeid == null) {
            if (other.employeeid != null)
                return false;
        } else if (!employeeid.equals(other.employeeid))
            return false;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (operation == null) {
            if (other.operation != null)
                return false;
        } else if (!operation.equals(other.operation))
            return false;
        if (operationdesc == null) {
            if (other.operationdesc != null)
                return false;
        } else if (!operationdesc.equals(other.operationdesc))
            return false;
        if (parentid == null) {
            if (other.parentid != null)
                return false;
        } else if (!parentid.equals(other.parentid))
            return false;
        if (result == null) {
            if (other.result != null)
                return false;
        } else if (!result.equals(other.result))
            return false;
        if (resultdesc == null) {
            if (other.resultdesc != null)
                return false;
        } else if (!resultdesc.equals(other.resultdesc))
            return false;
        if (sourcemodule == null) {
            if (other.sourcemodule != null)
                return false;
        } else if (!sourcemodule.equals(other.sourcemodule))
            return false;
        if (target == null) {
            if (other.target != null)
                return false;
        } else if (!target.equals(other.target))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        } else if (!username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "TOperationLogWResult [id=" + id + ", parentid=" + parentid + ", employeeid=" + employeeid
                + ", username=" + username + ", sourcemodule=" + sourcemodule + ", operation=" + operation
                + ", operationdesc=" + operationdesc + ", target=" + target + ", description=" + description
                + ", result=" + result + ", resultdesc=" + resultdesc + ", createdate=" + createdate + ", createtime="
                + createtime + "]";
    }

}