package com.mgskj.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 * 
 * @author shenchanghui
 *
 */
public class TVDDataCenterResult implements Serializable {

	public TVDDataCenterResult() {
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table T_VD_Data_Hour
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private String equipId;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "HH:mm", timezone = "GMT+8")
	private Date gathertime;

	private String equipName;

	private int bSmallForward;

	private int bBigForward;

	private int bAllForward;

	private double bSmallAvgSpd;

	private double bBigAvgSpd;

	private double bAllAvgSpd;

	private double bsmallOccupancy;

	private double bBigOccupancy;

	private double bAllOccupancy;

	private int aSmallForward;

	private int aBigForward;

	private int aAllForward;

	private double aSmallAvgSpd;

	private double aBigAvgSpd;

	private double aAllAvgSpd;

	private double asmallOccupancy;

	private double aBigOccupancy;

	private double aAllOccupancy;

	private int count;

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getEquipId() {
		return equipId;
	}

	public void setEquipId(String equipId) {
		this.equipId = equipId;
	}

	public Date getGathertime() {
		return gathertime;
	}

	public void setGathertime(Date gathertime) {
		this.gathertime = gathertime;
	}

	public String getEquipName() {
		return equipName;
	}

	public void setEquipName(String equipName) {
		this.equipName = equipName;
	}

	public int getbSmallForward() {
		return bSmallForward;
	}

	public void setbSmallForward(int bSmallForward) {
		this.bSmallForward = bSmallForward;
	}

	public int getbBigForward() {
		return bBigForward;
	}

	public void setbBigForward(int bBigForward) {
		this.bBigForward = bBigForward;
	}

	public int getbAllForward() {
		return bAllForward;
	}

	public void setbAllForward(int bAllForward) {
		this.bAllForward = bAllForward;
	}

	public double getbSmallAvgSpd() {
		return bSmallAvgSpd;
	}

	public void setbSmallAvgSpd(double bSmallAvgSpd) {
		this.bSmallAvgSpd = bSmallAvgSpd;
	}

	public double getbBigAvgSpd() {
		return bBigAvgSpd;
	}

	public void setbBigAvgSpd(double bBigAvgSpd) {
		this.bBigAvgSpd = bBigAvgSpd;
	}

	public double getbAllAvgSpd() {
		return bAllAvgSpd;
	}

	public void setbAllAvgSpd(double bAllAvgSpd) {
		this.bAllAvgSpd = bAllAvgSpd;
	}

	public double getBsmallOccupancy() {
		return bsmallOccupancy;
	}

	public void setBsmallOccupancy(double bsmallOccupancy) {
		this.bsmallOccupancy = bsmallOccupancy;
	}

	public double getbBigOccupancy() {
		return bBigOccupancy;
	}

	public void setbBigOccupancy(double bBigOccupancy) {
		this.bBigOccupancy = bBigOccupancy;
	}

	public double getbAllOccupancy() {
		return bAllOccupancy;
	}

	public void setbAllOccupancy(double bAllOccupancy) {
		this.bAllOccupancy = bAllOccupancy;
	}

	public int getaSmallForward() {
		return aSmallForward;
	}

	public void setaSmallForward(int aSmallForward) {
		this.aSmallForward = aSmallForward;
	}

	public int getaBigForward() {
		return aBigForward;
	}

	public void setaBigForward(int aBigForward) {
		this.aBigForward = aBigForward;
	}

	public int getaAllForward() {
		return aAllForward;
	}

	public void setaAllForward(int aAllForward) {
		this.aAllForward = aAllForward;
	}

	public double getaSmallAvgSpd() {
		return aSmallAvgSpd;
	}

	public void setaSmallAvgSpd(double aSmallAvgSpd) {
		this.aSmallAvgSpd = aSmallAvgSpd;
	}

	public double getaBigAvgSpd() {
		return aBigAvgSpd;
	}

	public void setaBigAvgSpd(double aBigAvgSpd) {
		this.aBigAvgSpd = aBigAvgSpd;
	}

	public double getaAllAvgSpd() {
		return aAllAvgSpd;
	}

	public void setaAllAvgSpd(double aAllAvgSpd) {
		this.aAllAvgSpd = aAllAvgSpd;
	}

	public double getAsmallOccupancy() {
		return asmallOccupancy;
	}

	public void setAsmallOccupancy(double asmallOccupancy) {
		this.asmallOccupancy = asmallOccupancy;
	}

	public double getaBigOccupancy() {
		return aBigOccupancy;
	}

	public void setaBigOccupancy(double aBigOccupancy) {
		this.aBigOccupancy = aBigOccupancy;
	}

	public double getaAllOccupancy() {
		return aAllOccupancy;
	}

	public void setaAllOccupancy(double aAllOccupancy) {
		this.aAllOccupancy = aAllOccupancy;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(aAllAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + aAllForward;
		temp = Double.doubleToLongBits(aAllOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(aBigAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + aBigForward;
		temp = Double.doubleToLongBits(aBigOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(aSmallAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + aSmallForward;
		temp = Double.doubleToLongBits(asmallOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(bAllAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + bAllForward;
		temp = Double.doubleToLongBits(bAllOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(bBigAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + bBigForward;
		temp = Double.doubleToLongBits(bBigOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(bSmallAvgSpd);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + bSmallForward;
		temp = Double.doubleToLongBits(bsmallOccupancy);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((equipId == null) ? 0 : equipId.hashCode());
		result = prime * result + ((equipName == null) ? 0 : equipName.hashCode());
		result = prime * result + ((gathertime == null) ? 0 : gathertime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TVDDataCenterResult other = (TVDDataCenterResult) obj;
		if (Double.doubleToLongBits(aAllAvgSpd) != Double.doubleToLongBits(other.aAllAvgSpd))
			return false;
		if (aAllForward != other.aAllForward)
			return false;
		if (Double.doubleToLongBits(aAllOccupancy) != Double.doubleToLongBits(other.aAllOccupancy))
			return false;
		if (Double.doubleToLongBits(aBigAvgSpd) != Double.doubleToLongBits(other.aBigAvgSpd))
			return false;
		if (aBigForward != other.aBigForward)
			return false;
		if (Double.doubleToLongBits(aBigOccupancy) != Double.doubleToLongBits(other.aBigOccupancy))
			return false;
		if (Double.doubleToLongBits(aSmallAvgSpd) != Double.doubleToLongBits(other.aSmallAvgSpd))
			return false;
		if (aSmallForward != other.aSmallForward)
			return false;
		if (Double.doubleToLongBits(asmallOccupancy) != Double.doubleToLongBits(other.asmallOccupancy))
			return false;
		if (Double.doubleToLongBits(bAllAvgSpd) != Double.doubleToLongBits(other.bAllAvgSpd))
			return false;
		if (bAllForward != other.bAllForward)
			return false;
		if (Double.doubleToLongBits(bAllOccupancy) != Double.doubleToLongBits(other.bAllOccupancy))
			return false;
		if (Double.doubleToLongBits(bBigAvgSpd) != Double.doubleToLongBits(other.bBigAvgSpd))
			return false;
		if (bBigForward != other.bBigForward)
			return false;
		if (Double.doubleToLongBits(bBigOccupancy) != Double.doubleToLongBits(other.bBigOccupancy))
			return false;
		if (Double.doubleToLongBits(bSmallAvgSpd) != Double.doubleToLongBits(other.bSmallAvgSpd))
			return false;
		if (bSmallForward != other.bSmallForward)
			return false;
		if (Double.doubleToLongBits(bsmallOccupancy) != Double.doubleToLongBits(other.bsmallOccupancy))
			return false;
		if (equipId == null) {
			if (other.equipId != null)
				return false;
		} else if (!equipId.equals(other.equipId))
			return false;
		if (equipName == null) {
			if (other.equipName != null)
				return false;
		} else if (!equipName.equals(other.equipName))
			return false;
		if (gathertime == null) {
			if (other.gathertime != null)
				return false;
		} else if (!gathertime.equals(other.gathertime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TVDDataCenterResult [equipId=" + equipId + ", gathertime=" + gathertime + ", equipName=" + equipName
				+ ", bSmallForward=" + bSmallForward + ", bBigForward=" + bBigForward + ", bAllForward=" + bAllForward
				+ ", bSmallAvgSpd=" + bSmallAvgSpd + ", bBigAvgSpd=" + bBigAvgSpd + ", bAllAvgSpd=" + bAllAvgSpd
				+ ", bsmallOccupancy=" + bsmallOccupancy + ", bBigOccupancy=" + bBigOccupancy + ", bAllOccupancy="
				+ bAllOccupancy + ", aSmallForward=" + aSmallForward + ", aBigForward=" + aBigForward + ", aAllForward="
				+ aAllForward + ", aSmallAvgSpd=" + aSmallAvgSpd + ", aBigAvgSpd=" + aBigAvgSpd + ", aAllAvgSpd="
				+ aAllAvgSpd + ", asmallOccupancy=" + asmallOccupancy + ", aBigOccupancy=" + aBigOccupancy
				+ ", aAllOccupancy=" + aAllOccupancy + "]";
	}

}