package com.mgskj.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 车检器
 * 
 * @author shenchanghui
 *
 */
public class TVDDataStationHourResult implements Serializable {

	public TVDDataStationHourResult() {
	}

	private Integer forward;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_VD_Data_Hour.GatherTime
	 *
	 * @mbggenerated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern = "HH", timezone = "GMT+8")
	private Date gathertime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table T_VD_Data_Hour
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private String equipname;

	public Integer getForward() {
		return forward;
	}

	public void setForward(Integer forward) {
		this.forward = forward;
	}

	public Date getGathertime() {
		return gathertime;
	}

	public void setGathertime(Date gathertime) {
		this.gathertime = gathertime;
	}

	public String getEquipname() {
		return equipname;
	}

	public void setEquipname(String equipname) {
		this.equipname = equipname;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((equipname == null) ? 0 : equipname.hashCode());
		result = prime * result + ((forward == null) ? 0 : forward.hashCode());
		result = prime * result + ((gathertime == null) ? 0 : gathertime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TVDDataStationHourResult other = (TVDDataStationHourResult) obj;
		if (equipname == null) {
			if (other.equipname != null)
				return false;
		} else if (!equipname.equals(other.equipname))
			return false;
		if (forward == null) {
			if (other.forward != null)
				return false;
		} else if (!forward.equals(other.forward))
			return false;
		if (gathertime == null) {
			if (other.gathertime != null)
				return false;
		} else if (!gathertime.equals(other.gathertime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TVDDataStationHourResult [forward=" + forward + ", gathertime=" + gathertime + ", equipname="
				+ equipname + "]";
	}

}