package com.mgskj.dao;

import com.mgskj.model.HTOrganizationInfo;

import java.util.List;

public interface HTOrganizationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    int insert(HTOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    int insertSelective(HTOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    HTOrganizationInfo selectByPrimaryKey(String orgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HTOrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OrganizationInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HTOrganizationInfo record);

    /**
     * 根据id获取机维站列表
     */
    List<HTOrganizationInfo> getStationListById(String orgid);
}