package com.mgskj.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mgskj.bean.ETEquipResult;
import com.mgskj.model.TETEquip;
import com.mgskj.model.TRegionInfo;

public interface TETEquipMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int insert(TETEquip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int insertSelective(TETEquip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    TETEquip selectByPrimaryKey(String id);

    List<ETEquipResult> selectETEquip(@Param("map") Map<String, Object> map);

    List<TRegionInfo> selectRegionName(@Param("routeCode") String routeCode);

    /**
     * 设备名称
     *
     * @return
     */
    List<TETEquip> selectEquipName(@Param("routeCode") String routeCode, @Param("regionId") String regionId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TETEquip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TETEquip record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_ET_Equip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TETEquip record);
}