package com.mgskj.dao;

import com.mgskj.model.TEVDAlarmDataW;

public interface TEVDAlarmDataWMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    int insert(TEVDAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    int insertSelective(TEVDAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    TEVDAlarmDataW selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TEVDAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EVD_AlarmDataW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TEVDAlarmDataW record);
}