package com.mgskj.dao;

import com.mgskj.model.TFAAlarmDataW;

public interface TFAAlarmDataWMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    int insert(TFAAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    int insertSelective(TFAAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    TFAAlarmDataW selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TFAAlarmDataW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FA_AlarmDataW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TFAAlarmDataW record);
}