package com.mgskj.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mgskj.bean.ETEquipResult;
import com.mgskj.model.TFAEquip;
import com.mgskj.model.TRegionInfo;

public interface TFAEquipMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int insert(TFAEquip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int insertSelective(TFAEquip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	TFAEquip selectByPrimaryKey(String id);

	List<ETEquipResult> selectFAEquip(@Param("map") Map<String, Object> map);

	List<TRegionInfo> selectRegionName();

	List<TFAEquip> selectEquipName(@Param("routeCode") String routeCode, @Param("regionId") String regionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TFAEquip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(TFAEquip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_FA_Equip
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TFAEquip record);
}