package com.mgskj.dao;

import com.mgskj.model.TOperationLogWCMSControlW;

public interface TOperationLogWCMSControlWMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    int insert(TOperationLogWCMSControlW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    int insertSelective(TOperationLogWCMSControlW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    TOperationLogWCMSControlW selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOperationLogWCMSControlW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_OperationLogW_CMS_ControlW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOperationLogWCMSControlW record);
}