package com.mgskj.dao;

import java.util.List;
import java.util.Map;

import com.mgskj.bean.*;
import org.apache.ibatis.annotations.Param;

import com.mgskj.model.TOperationLogW;

public interface TOperationLogWMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    int insert(TOperationLogW record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    int insertSelective(TOperationLogW record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    TOperationLogW selectByPrimaryKey(String id);

    List<UserName> selectUserName(@Param("map") Map<String, Object> map);

    List<BoardOperationResult> getBoardOperationList(@Param("map") Map<String, Object> map);

    List<ETOperationResult> getETOperationList(@Param("map") Map<String, Object> map);

    List<EVDOperationResult> getEVDOperationList(@Param("map") Map<String, Object> map);

    List<FAOperationResult> getFAOperationList(@Param("map") Map<String, Object> map);

    List<TOperationLogWResult> getLoginOperationList(@Param("map") Map<String, Object> map);

    List<TOperationLogWResult> getTunnelOperationList(@Param("map") Map<String, Object> map);

    List<TOperationLogWResult> getAlarmLinkOperationList(@Param("map") Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOperationLogW record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_OperationLogW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOperationLogW record);
}