package com.mgskj.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mgskj.model.TRegionInfo;

public interface TRegionInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int insert(TRegionInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int insertSelective(TRegionInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    TRegionInfo selectByPrimaryKey(String id);

    List<TRegionInfo> selectMachineStation(@Param("regionId") String regionId);

    List<TRegionInfo> selectPublicRegion(@Param("regionId") String regionId);

    TRegionInfo selectRegionInfoById(@Param("regionId") String regionId);

    List<TRegionInfo> selectRegionByRouteCode(@Param("map") Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRegionInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TRegionInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_RegionInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRegionInfo record);
}