package com.mgskj.dao;

import com.mgskj.model.TRelRegionRegion;

public interface TRelRegionRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int insert(TRelRegionRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int insertSelective(TRelRegionRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    TRelRegionRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRelRegionRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TRelRegionRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Rel_Region_Region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRelRegionRegion record);
}