package com.mgskj.dao;

import java.util.List;

import com.mgskj.model.UserName;

public interface TUserInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int insert(UserName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int insertSelective(UserName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	UserName selectByPrimaryKey(String id);

	List<UserName> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(UserName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_UserInfo
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserName record);
}