package com.mgskj.dao;

import com.mgskj.model.TVDDataRaw;
/**
 * 车检器报表
 * @author shenchanghui
 *
 */
public interface TVDDataRawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    int insert(TVDDataRaw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    int insertSelective(TVDDataRaw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    TVDDataRaw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TVDDataRaw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VD_Data_Raw
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TVDDataRaw record);
}