package com.mgskj.dao;

import com.mgskj.bean.TVDDataStationHourResult;
import com.mgskj.model.TVDDataHour;
import com.mgskj.model.TVDDataHourResult;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * 车检器报表
 *
 * @author shenchanghui
 */
public interface TVDDataHourMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    int insert(TVDDataHour record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    int insertSelective(TVDDataHour record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    TVDDataHour selectByPrimaryKey(Integer id);

    /**
     * 获取车检器日报表数据
     *
     * @return
     */
    List<TVDDataStationHourResult> selectHourList(@Param("regionCode") String regionCode, @Param("date") String date,
                                                  @Param("PrefixLength") String prefixLength);

    /**
     * 获取车检器信息中心报表数据
     *
     * @return
     */
    List<TVDDataHourResult> selectCenterList(@Param("map") Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TVDDataHour record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table T_VD_Data_Hour
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TVDDataHour record);
}