package com.mgskj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mgskj.model.TVDDataDay;
import com.mgskj.model.TVDDataDayResult;

/**
 * 车检器报表
 * 
 * @author shenchanghui
 *
 */
public interface TVDDataDayMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	int insert(TVDDataDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	int insertSelective(TVDDataDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	TVDDataDay selectByPrimaryKey(Integer id);

	/**
	 * 获取车检器月报表数据
	 * 
	 * @return
	 */
	List<TVDDataDayResult> selectDayList(@Param("regionCode") String regionCode, @Param("date") String date,
			@Param("PrefixLength") String prefixLength);

	/**
	 * 获取车检器年报表数据
	 * 
	 * @return
	 */
	List<TVDDataDayResult> selectMonthList(@Param("regionCode") String regionCode, @Param("date") String date,
			@Param("PrefixLength") String prefixLength);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TVDDataDay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_VD_Data_Day
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TVDDataDay record);
}